import type { PackForm } from "@/components/constructor/packForms";

/** Формы блоков «Стандарта»: подписки. */
export const DEFAULT_SUBSCRIPTION_FORMS: Record<string, PackForm> = {
  defaultInvoiceList: [
    {
      title: { ru: "Тексты", en: "Texts" },
      description: { ru: "Тянет данные из /api/payments.", en: "Reads data from /api/payments." },
      fields: [
        { kind: "text", key: "panelHeader", label: { ru: "Заголовок", en: "Header" }, placeholder: "// Транзакции" },
        { kind: "text", key: "panelHeaderHintFormat", label: { ru: "Хинт-формат ({count})", en: "Hint format ({count})" }, placeholder: "{count} записей" },
        { kind: "text", key: "paidLabel", label: { ru: "Pill: оплачено", en: "Pill: paid" }, placeholder: "PAID" },
        { kind: "text", key: "failedLabel", label: { ru: "Pill: ошибка", en: "Pill: failed" }, placeholder: "Не оплачено" },
        { kind: "text", key: "pdfLabel", label: { ru: "Ссылка на PDF", en: "PDF link" }, placeholder: "↓ PDF" },
        { kind: "text", key: "prevLabel", label: { ru: "Кнопка «назад»", en: "Prev label" }, placeholder: "← НАЗАД" },
        { kind: "text", key: "nextLabel", label: { ru: "Кнопка «вперёд»", en: "Next label" }, placeholder: "ВПЕРЁД →" },
        { kind: "text", key: "pageLabelFormat", label: { ru: "Формат счётчика страниц ({page} / {total})", en: "Page label ({page}/{total})" }, placeholder: "{page} / {total}" },
        { kind: "text", key: "emptyText", label: { ru: "Пусто", en: "Empty" }, placeholder: "Платежей пока нет" },
        { kind: "text", key: "unauthenticatedText", label: { ru: "Не авторизован", en: "Not authed" } },
        { kind: "boolean", key: "showAdjustments", label: { ru: "Показывать начисления (админ, рефералы, кэшбек, купоны)", en: "Show adjustments (admin, referrals, cashback, coupons)" } },
        { kind: "number", key: "pageSize", label: { ru: "Платежей на странице", en: "Items per page" }, min: 1, max: 100, default: 5 },
        { kind: "number", key: "maxItems", label: { ru: "Всего загружать (макс.)", en: "Max total items" }, min: 1, max: 200, default: 200 },
      ],
    },
    {
      title: "Ссылка на все платежи",
      tab: "data",
      fields: [
        { kind: "text", key: "allLabel", label: { ru: "Подпись ссылки", en: "Link label" }, placeholder: "Все платежи" },
        { kind: "text", key: "allHref", label: { ru: "Куда ведёт", en: "Link href" }, placeholder: "/dashboard/profile" },
      ],
    },
  ],
  defaultPaymentMethod: [
    {
      title: { ru: "Карта", en: "Card" },
      description: { ru: "Маска карты и подпись.", en: "Card mask and meta." },
      fields: [
        { kind: "text", key: "panelHeader", label: { ru: "Заголовок", en: "Header" }, placeholder: "// Метод оплаты" },
        { kind: "text", key: "panelHeaderHint", label: { ru: "Хинт", en: "Hint" }, placeholder: "основной" },
        { kind: "text", key: "cardMask", label: { ru: "Маска карты", en: "Card mask" }, placeholder: "•••• •••• •••• 4 829" },
        { kind: "text", key: "cardMeta", label: { ru: "Подпись", en: "Card meta" }, placeholder: "VISA · ИСТЕКАЕТ 11/28" },
        { kind: "text", key: "changeLabel", label: { ru: "Кнопка «Сменить»", en: "Change label" }, placeholder: "Сменить" },
        { kind: "text", key: "changeHref", label: { ru: "Ссылка кнопки", en: "Change href" }, placeholder: "/dashboard/profile" },
        { kind: "text", key: "altMethodsLabel", label: { ru: "Заголовок альт-методов", en: "Alt methods label" }, placeholder: "// Альтернативные методы" },
      ],
    },
    {
      title: { ru: "Альтернативные методы", en: "Alternative methods" },
      description: { ru: "Чипы под карточкой.", en: "Chips under the card." },
      fields: [
        { kind: "list", key: "altMethods", label: { ru: "Методы", en: "Methods" }, addLabel: { ru: "Метод", en: "Method" }, newItem: { label: "" }, item: [{ kind: "text", key: "label", label: { ru: "Название", en: "Label" } }] },
      ],
    },
    {
      title: "Сводка по платежам",
      fields: [
        { kind: "text", key: "paymentsCountLabel", label: { ru: "Подпись «платежей»", en: "Payments count label" }, placeholder: "Платежей" },
        { kind: "text", key: "totalSpentLabel", label: { ru: "Подпись «всего оплачено»", en: "Total spent label" }, placeholder: "Всего оплачено" },
        { kind: "text", key: "noPaymentsText", label: { ru: "Платежей нет", en: "No payments" }, placeholder: "Платежей пока нет" },
      ],
    },
  ],
  defaultTariffPanel: [
    {
      title: { ru: "Шапка панели", en: "Panel header" },
      description: { ru: "Хинт оставь пустым — возьмётся имя текущего тарифа из API.", en: "Leave hint empty — current tariff name pulled from API." },
      fields: [
        { kind: "text", key: "panelHeader", label: { ru: "Заголовок", en: "Header" }, placeholder: "// Текущий тариф" },
        { kind: "text", key: "panelHeaderHint", label: { ru: "Хинт (override имени тарифа)", en: "Hint (tariff name override)" }, placeholder: "оставь пустым" },
      ],
    },
    {
      title: { ru: "Подключение (VPN)", en: "Connect (VPN)" },
      description: { ru: "Секция подключения внутри блока: ключ, ссылка, кнопки Подключить/Поделиться/QR.", en: "Connect section inside the block: key, link, Connect/Share/QR buttons." },
      fields: [
        { kind: "text", key: "connectHint", label: { ru: "Хинт сверху", en: "Top hint" }, placeholder: "Подключение к VPN" },
        { kind: "text", key: "connectSubtitleText", label: { ru: "Подпись под ключом", en: "Key subtitle" }, placeholder: "Ключ доступа к подписке" },
        { kind: "text", key: "connectLabel", label: { ru: "Кнопка подключения", en: "Connect button" }, placeholder: "Подключить" },
        { kind: "text", key: "shareLabel", label: { ru: "Кнопка «Поделиться»", en: "Share button" }, placeholder: "Поделиться" },
        { kind: "text", key: "qrLabel", label: { ru: "Кнопка QR", en: "QR button" }, placeholder: "QR-код" },
        { kind: "text", key: "copyLabel", label: { ru: "Кнопка копирования", en: "Copy button" }, placeholder: "Копировать" },
        { kind: "text", key: "copiedLabel", label: { ru: "После копирования", en: "Copied label" }, placeholder: "Скопировано" },
        { kind: "text", key: "qrShareHint", label: { ru: "Подсказка под QR", en: "QR hint" }, placeholder: "Если хотите поделиться..." },
      ],
    },
    {
      title: { ru: "Подписи строк (фичи из API)", en: "Row labels (features from API)" },
      description: { ru: "Реальные значения тянутся из /api/keys/{id}/details.", en: "Real values come from /api/keys/{id}/details." },
      fields: [
        { kind: "text", key: "labelAlias", label: { ru: "Имя подписки", en: "Alias label" }, placeholder: "Имя" },
        { kind: "text", key: "labelDevices", label: { ru: "Устройств", en: "Devices label" }, placeholder: "Устройств" },
        { kind: "text", key: "labelTraffic", label: { ru: "Трафик", en: "Traffic label" }, placeholder: "Трафик" },
        { kind: "text", key: "labelExpiry", label: { ru: "До", en: "Expiry label" }, placeholder: "До" },
        { kind: "text", key: "renewalPrefix", label: { ru: "Префикс «Истекает»", en: "Expires prefix" }, placeholder: "Истекает" },
        { kind: "text", key: "trafficUnlimitedText", label: { ru: "Текст безлимита", en: "Unlimited text" }, placeholder: "∞" },
      ],
    },
    {
      title: { ru: "Состояние «нет подписки»", en: "«No subscription» state" },
      fields: [
        { kind: "text", key: "noKeysText", label: { ru: "Текст-плейсхолдер", en: "Placeholder text" }, placeholder: "Нет активной подписки" },
        { kind: "text", key: "buyTariffLabel", label: { ru: "Кнопка купить", en: "Buy button" }, placeholder: "Купить тариф" },
      ],
    },
    {
      title: { ru: "Modal «Докупить» — тексты", en: "«Buy add-ons» modal — labels" },
      description: { ru: "Тексты внутри модального окна добавления опций.", en: "Labels inside the add-ons modal." },
      fields: [
        { kind: "text", key: "addonsDialogTitle", label: { ru: "Заголовок modal", en: "Modal title" }, placeholder: "Докупить опции" },
        { kind: "text", key: "addonsDialogHint", label: { ru: "Подсказка", en: "Subtitle" }, placeholder: "Доп. устройства/трафик к текущему тарифу" },
        { kind: "text", key: "addonsDevicesLabel", label: { ru: "Устройства label", en: "Devices label" }, placeholder: "Устройства" },
        { kind: "text", key: "addonsTrafficLabel", label: { ru: "Трафик label", en: "Traffic label" }, placeholder: "Трафик" },
        { kind: "text", key: "addonsTotalLabel", label: { ru: "Итого label", en: "Total label" }, placeholder: "Итого к оплате" },
        { kind: "text", key: "addonsSubmitLabel", label: { ru: "Кнопка submit", en: "Submit label" }, placeholder: "Оформить" },
        { kind: "text", key: "addonsCancelLabel", label: { ru: "Кнопка отмена", en: "Cancel label" }, placeholder: "Отмена" },
        { kind: "text", key: "addonsUnavailableText", label: { ru: "Опций нет", en: "No options" }, placeholder: "Для текущего тарифа нет доступных опций" },
        { kind: "text", key: "addonsDeviceUnitFormat", label: { ru: "Вариант устройств ({n})", en: "Device option ({n})" }, placeholder: "{n} устр." },
        { kind: "text", key: "addonsDeviceUnlimitedText", label: { ru: "Безлимит устройств", en: "Unlimited devices" }, placeholder: "∞ устр." },
        { kind: "text", key: "addonsTrafficUnitFormat", label: { ru: "Вариант трафика ({n})", en: "Traffic option ({n})" }, placeholder: "{n} ГБ" },
        { kind: "text", key: "addonsTrafficUnlimitedText", label: { ru: "Безлимит трафика", en: "Unlimited traffic" }, placeholder: "∞" },
      ],
    },
    {
      title: "Цена, продление и QR",
      fields: [
        { kind: "text", key: "currentTariffLabel", label: { ru: "Подпись «текущий тариф»", en: "Current tariff label" }, placeholder: "Текущий тариф" },
        { kind: "text", key: "pricePrimary", label: { ru: "Цена (если тариф не найден)", en: "Fallback price" }, placeholder: "399" },
        { kind: "text", key: "pricePeriodLabel", label: { ru: "Период цены", en: "Price period" }, placeholder: "₽ / мес" },
        { kind: "text", key: "progressActiveFormat", label: { ru: "Прогресс подписки", en: "Subscription progress" }, placeholder: "Осталось {leftDays}" },
        { kind: "text", key: "expiryUrgentFormat", label: { ru: "Скоро закончится", en: "Expiring soon" }, placeholder: "⚠️ Подписка заканчивается через {days}", multiline: true },
        { kind: "text", key: "renewalText", label: { ru: "Текст продления", en: "Renewal text" }, placeholder: "", multiline: true },
        { kind: "text", key: "renewalUpsellHint", label: { ru: "Подсказка про докупку", en: "Upsell hint" }, placeholder: "Нужно больше устройств или трафика?", multiline: true },
        { kind: "text", key: "renamePlaceholder", label: { ru: "Плейсхолдер имени подписки", en: "Alias placeholder" }, placeholder: "Имя подписки" },
        { kind: "text", key: "shareTitle", label: { ru: "Заголовок при отправке", en: "Share title" }, placeholder: "Подключение к VPN" },
        { kind: "text", key: "qrLoadingText", label: { ru: "QR: загрузка", en: "QR loading" }, placeholder: "Загрузка..." },
        { kind: "text", key: "qrErrorText", label: { ru: "QR: ошибка", en: "QR error" }, placeholder: "Не удалось загрузить QR" },
        { kind: "text", key: "qrCloseLabel", label: { ru: "QR: закрыть", en: "QR close" }, placeholder: "Закрыть QR" },
        { kind: "boolean", key: "showConnect", label: { ru: "Кнопка «Подключить»", en: "«Connect» button" }, default: true },
        { kind: "boolean", key: "showCopy", label: { ru: "Кнопка «Копировать»", en: "«Copy» button" }, default: true },
        { kind: "number", key: "expiryUrgentDays", label: { ru: "За сколько дней предупреждать", en: "Warn days before expiry" }, min: 0, max: 90, default: 3 },
      ],
    },
    {
      title: "Склонение дней",
      description: "Три формы через слэш: 1 день / 2 дня / 5 дней.",
      fields: [
        { kind: "text", key: "dayForms", label: { ru: "Дни", en: "Days" }, placeholder: "день/дня/дней" },
      ],
    },
    {
      title: { ru: "Кнопки подключения", en: "Connect buttons" },
      tab: "data",
      description: { ru: "Что показывать в секции подключения блока.", en: "What to show in the block connect section." },
      fields: [
        { kind: "boolean", key: "showConnectSection", label: { ru: "Показывать секцию подключения", en: "Show connect section" }, default: true },
        { kind: "boolean", key: "showLink", label: { ru: "Показывать ссылку с копированием", en: "Show link with copy" }, default: true },
        { kind: "boolean", key: "showShare", label: { ru: "Кнопка «Поделиться»", en: "Share button" }, default: true },
        { kind: "boolean", key: "showQr", label: { ru: "Кнопка QR", en: "QR button" }, default: true },
        { kind: "boolean", key: "showRename", label: { ru: "Переименование ключа", en: "Key rename" }, default: true },
      ],
    },
    {
      title: { ru: "Кнопка «Продлить»", en: "«Renew» button" },
      tab: "data",
      description: { ru: "Дефолт автоматически генерирует /checkout?subKey=...&flow=renew. Свой URL переопределяет.", en: "Default auto-generates /checkout?subKey=...&flow=renew. Custom URL overrides." },
      fields: [
        { kind: "text", key: "primaryButtonLabel", label: { ru: "Текст кнопки", en: "Label" }, placeholder: "Продлить" },
        { kind: "text", key: "primaryButtonHref", label: { ru: "Свой URL (опционально)", en: "Custom URL (optional)" }, placeholder: "пусто = авто /checkout" },
      ],
    },
    {
      title: { ru: "Кнопка «Докупить опции»", en: "«Buy add-ons» button" },
      tab: "data",
      description: { ru: "Открывает modal с устройствами/трафиком из API текущего тарифа. Если URL задан — modal не открывается, идёт redirect.", en: "Opens modal with devices/traffic options from current tariff API. If URL set — no modal, just redirect." },
      fields: [
        { kind: "text", key: "addonsButtonLabel", label: { ru: "Текст кнопки", en: "Label" }, placeholder: "Докупить" },
        { kind: "text", key: "addonsButtonHref", label: { ru: "Свой URL (отключает modal)", en: "Custom URL (disables modal)" }, placeholder: "пусто = открыть modal" },
      ],
    },
    {
      title: { ru: "Кнопка «Сменить тариф»", en: "«Switch tariff» button" },
      tab: "data",
      description: { ru: "Можно: показать список тарифов прямо в блоке (по умолчанию), переключить экран раздела или вести на отдельную страницу.", en: "Show tariff list inline (default), switch section screen, or navigate to a separate page." },
      fields: [
        { kind: "text", key: "switchTariffLabel", label: { ru: "Текст кнопки", en: "Label" }, placeholder: "Сменить тариф" },
        { kind: "select", key: "checkoutSlug", label: { ru: "[inside] Slug страницы checkout", en: "[inside] Checkout slug" }, source: "pages", allowEmpty: true, emptyLabel: { ru: "Страница по умолчанию", en: "Default page" }, allowCustom: true, customPlaceholder: { ru: "checkout", en: "checkout" } },
        { kind: "text", key: "switchTariffScreenGroup", label: { ru: "[screen] Группа экрана", en: "[screen] Screen group" }, placeholder: "tariffs" },
        { kind: "text", key: "switchTariffScreenId", label: { ru: "[screen] ID экрана", en: "[screen] Screen ID" }, placeholder: "switch" },
        { kind: "text", key: "switchTariffHref", label: { ru: "[page] URL страницы", en: "[page] Page URL" }, placeholder: "/tariffs" },
        { kind: "text", key: "switchTariffBackLabel", label: { ru: "Кнопка «Назад»", en: "Back button" }, placeholder: "← Назад" },
        { kind: "text", key: "switchTariffEmptyText", label: { ru: "Текст «нет тарифов»", en: "Empty text" }, placeholder: "Доступных тарифов нет" },
        { kind: "text", key: "switchTariffCurrentBadge", label: { ru: "Бейдж текущего", en: "Current badge" }, placeholder: "ТЕКУЩИЙ" },
        { kind: "text", key: "switchTariffUpgradeLabel", label: { ru: "Кнопка перехода", en: "Switch button" }, placeholder: "Перейти →" },
        { kind: "text", key: "switchTariffSelectLabel", label: { ru: "Кнопка выбора (без подписки)", en: "Select button (no sub)" }, placeholder: "Выбрать" },
        { kind: "text", key: "switchTariffPerDayLabel", label: { ru: "Подпись «в день»", en: "Per-day label" }, placeholder: "в день" },
        { kind: "text", key: "switchTariffPageLabel", label: { ru: "Подпись страниц (для доступности)", en: "Page label (a11y)" }, placeholder: "Страница" },
        { kind: "select", key: "switchTariffMode", label: { ru: "Где открывать", en: "Where to open" }, default: "inside", options: [{ value: "inside", label: { ru: "Внутри блока (default)", en: "Inside block (default)" } }, { value: "screen", label: { ru: "Экран раздела", en: "Section screen" } }, { value: "page", label: { ru: "Отдельная страница", en: "Separate page" } }] },
        { kind: "select", key: "switchTariffGroupCode", label: { ru: "Группа тарифов для смены", en: "Group for switching" }, source: "tariffGroups", allowEmpty: true, allowCustom: true, emptyLabel: { ru: "Как у подписки", en: "Same as subscription" }, customPlaceholder: { ru: "Код группы или пусто", en: "Group code or empty" } },
      ],
    },
  ],
  defaultTariffSwitcher: [
    {
      title: { ru: "Шапка", en: "Header" },
      fields: [
        { kind: "text", key: "panelHeader", label: { ru: "Заголовок", en: "Header" }, placeholder: "// Сменить тариф" },
        { kind: "text", key: "panelHeaderHint", label: { ru: "Хинт", en: "Hint" }, placeholder: "выбери план" },
      ],
    },
    {
      title: { ru: "Состояния", en: "States" },
      fields: [
        { kind: "text", key: "loadingText", label: { ru: "Загрузка", en: "Loading" }, placeholder: "Загрузка..." },
        { kind: "text", key: "emptyText", label: { ru: "Пусто", en: "Empty" }, placeholder: "Тарифы не найдены" },
        { kind: "text", key: "errorText", label: { ru: "Ошибка", en: "Error" }, placeholder: "Не удалось загрузить тарифы" },
      ],
    },
    {
      title: { ru: "Кнопки", en: "Buttons" },
      fields: [
        { kind: "text", key: "currentBadge", label: { ru: "Бейдж текущего", en: "Current badge" }, placeholder: "ТЕКУЩИЙ" },
        { kind: "text", key: "upgradeLabel", label: { ru: "Кнопка апгрейд", en: "Upgrade label" }, placeholder: "Перейти →" },
        { kind: "text", key: "switchLabel", label: { ru: "Кнопка смены", en: "Switch label" }, placeholder: "Выбрать" },
        { kind: "text", key: "selectLabel", label: { ru: "Кнопка покупки", en: "Buy label" }, placeholder: "Купить" },
      ],
    },
    {
      title: { ru: "Параметры тарифа", en: "Tariff metrics" },
      fields: [
        { kind: "text", key: "perDayLabel", label: { ru: "Подпись «в день»", en: "Per-day label" }, placeholder: "в день" },
        { kind: "text", key: "pageLabel", label: { ru: "Подпись страниц (для доступности)", en: "Page label (a11y)" }, placeholder: "Страница" },
        { kind: "text", key: "devicesLabel", label: { ru: "Подпись устройств", en: "Devices label" }, placeholder: "устр." },
        { kind: "text", key: "trafficLabel", label: { ru: "Подпись трафика", en: "Traffic label" }, placeholder: "ГБ" },
        { kind: "text", key: "unlimitedText", label: { ru: "Текст безлимита", en: "Unlimited text" }, placeholder: "∞" },
      ],
    },
    {
      title: { ru: "Раскладка", en: "Layout" },
      tab: "style",
      fields: [
        { kind: "number", key: "compactListFrom", label: { ru: "Список вместо карточек от N тарифов", en: "Switch to list from N tariffs" }, min: 1, max: 50, default: 2 },
      ],
    },
    {
      title: { ru: "Источник тарифов", en: "Tariff source" },
      tab: "data",
      description: { ru: "Фильтр по группе и slug страницы checkout.", en: "Group filter and checkout slug." },
      fields: [
        { kind: "select", key: "groupCode", label: { ru: "Код группы (фильтр)", en: "Group code (filter)" }, source: "tariffGroups", allowEmpty: true, allowCustom: true, emptyLabel: { ru: "Все группы", en: "All groups" }, customPlaceholder: { ru: "Код группы или пусто = все", en: "Group code or empty = all" } },
        {
          kind: "select",
          key: "subgroupMode",
          label: { ru: "Подгруппы тарифов", en: "Tariff subgroups" },
          options: [
            { value: "all", label: { ru: "Показывать все подряд", en: "Show all at once" } },
            { value: "tabs", label: { ru: "Переключателем подгрупп", en: "With a subgroup switcher" } },
            { value: "one", label: { ru: "Только одну подгруппу", en: "A single subgroup only" } },
          ],
          default: "all",
        },
        {
          kind: "select",
          key: "subgroup",
          label: { ru: "Какая подгруппа", en: "Which subgroup" },
          source: "tariffSubgroups",
          allowEmpty: true,
          emptyLabel: { ru: "— выберите подгруппу —", en: "— pick a subgroup —" },
          when: { key: "subgroupMode", equals: "one" },
        },
        {
          kind: "text",
          key: "subgroupOtherLabel",
          label: { ru: "Подпись вкладки «остальные»", en: "The “other” tab label" },
          placeholder: "Остальные",
          when: { key: "subgroupMode", equals: "tabs" },
        },
        { kind: "select", key: "checkoutSlug", label: { ru: "Slug страницы checkout", en: "Checkout slug" }, source: "pages", allowEmpty: true, emptyLabel: { ru: "Страница по умолчанию", en: "Default page" }, allowCustom: true, customPlaceholder: { ru: "checkout", en: "checkout" } },
      ],
    },
    {
      title: "Смена тарифа",
      fields: [
        { kind: "text", key: "switchTitle", label: { ru: "Заголовок экрана", en: "Screen title" }, placeholder: "Смена тарифа" },
        { kind: "text", key: "switchPrimaryLabel", label: { ru: "Кнопка подтверждения", en: "Confirm button" }, placeholder: "Подтвердить смену" },
        { kind: "text", key: "switchProceedHint", label: { ru: "Предупреждение", en: "Warning" }, placeholder: "При смене тарифа счётчик трафика обнулится", multiline: true },
        { kind: "text", key: "switchPayLine", label: { ru: "Строка «к оплате»", en: "Amount due line" }, placeholder: "К оплате: {net} ₽." },
        { kind: "text", key: "switchCreditLine", label: { ru: "Строка про остаток", en: "Credit line" }, placeholder: "Неиспользованный остаток", multiline: true },
        { kind: "text", key: "switchCreditDaysLine", label: { ru: "Строка про остаток в днях", en: "Credit days line" }, placeholder: "Неиспользованный остаток — {credit}", multiline: true },
        { kind: "text", key: "switchKeepPeriodLine", label: { ru: "Срок сохраняется", en: "Period kept line" }, placeholder: "Срок подписки сохранится", multiline: true },
        { kind: "text", key: "switchRefundLine", label: { ru: "Строка про возврат на баланс", en: "Refund line" }, placeholder: "Доплачивать не нужно", multiline: true },
        { kind: "text", key: "switchDoneTitle", label: { ru: "Готово: заголовок", en: "Done title" }, placeholder: "Тариф изменён ✅" },
        { kind: "text", key: "switchDoneCreditLine", label: { ru: "Готово: зачислено на баланс", en: "Done credit line" }, placeholder: "На баланс зачислено {credit} ₽", multiline: true },
        { kind: "text", key: "switchDoneButton", label: { ru: "Готово: кнопка", en: "Done button" }, placeholder: "Готово" },
        { kind: "text", key: "switchErrorText", label: { ru: "Ошибка смены", en: "Switch error" }, placeholder: "Не удалось сменить тариф", multiline: true },
        { kind: "text", key: "backLabel", label: { ru: "Кнопка «Назад»", en: "Back button" }, placeholder: "← Назад" },
        { kind: "text", key: "downgradeLabel", label: { ru: "Кнопка понижения тарифа", en: "Downgrade button" }, placeholder: "Сменить" },
        { kind: "text", key: "fromPriceLabel", label: { ru: "Префикс цены", en: "Price prefix" }, placeholder: "от" },
        { kind: "text", key: "priceComputingText", label: { ru: "Цена считается", en: "Price computing" }, placeholder: "..." },
        { kind: "text", key: "optionsDevicesLabel", label: { ru: "Опции: устройства", en: "Options: devices" }, placeholder: "Устройств" },
        { kind: "text", key: "optionsTrafficLabel", label: { ru: "Опции: трафик", en: "Options: traffic" }, placeholder: "Трафик" },
        { kind: "boolean", key: "showGroupTabs", label: { ru: "Табы групп тарифов", en: "Tariff group tabs" }, default: true },
      ],
    },
  ],
  defaultTrialCard: [
    {
      title: { ru: "Тексты", en: "Texts" },
      description: { ru: "Подписи карточки. Сам тариф берётся автоматически из группы trial.", en: "Card labels. The tariff is taken automatically from the trial group." },
      fields: [
        { kind: "text", key: "panelHint", label: { ru: "Hint", en: "Hint" }, placeholder: "// пробный доступ" },
        { kind: "text", key: "titleText", label: { ru: "Заголовок", en: "Title" }, placeholder: "Пробный период" },
        { kind: "text", key: "ctaLabel", label: { ru: "Кнопка", en: "Button" }, placeholder: "Попробовать" },
        { kind: "text", key: "freeLabel", label: { ru: "Метка «бесплатно»", en: "Free label" }, placeholder: "Бесплатно" },
        { kind: "text", key: "usedLabel", label: { ru: "Уже использован", en: "Already used" }, placeholder: "Уже использован" },
        { kind: "text", key: "noTrialText", label: { ru: "Нет тарифа", en: "No tariff" }, placeholder: "Нет пробного тарифа в группе trial" },
        { kind: "text", key: "loadingText", label: { ru: "Загрузка", en: "Loading" }, placeholder: "Загрузка..." },
        { kind: "text", key: "devicesUnit", label: { ru: "Ед. устройств", en: "Devices unit" }, placeholder: "устр." },
        { kind: "text", key: "trafficUnit", label: { ru: "Ед. трафика", en: "Traffic unit" }, placeholder: "ГБ" },
        { kind: "text", key: "unlimitedText", label: { ru: "Безлимит", en: "Unlimited" }, placeholder: "∞" },
      ],
    },
    {
      title: "Ошибки пробной подписки",
      fields: [
        { kind: "text", key: "trialErrorText", label: { ru: "Ошибка активации", en: "Activation error" }, placeholder: "Не удалось активировать пробную подписку", multiline: true },
      ],
    },
  ],
};
