from api.v1.schemas import (
    BlockedUserResponse,
    CouponBase,
    CouponResponse,
    CouponUpdate,
    CouponUsageResponse,
    GiftBase,
    GiftResponse,
    GiftUpdate,
    GiftUsageResponse,
    KeyDetailsResponse,
    KeyResponse,
    ManualBanResponse,
    NotificationResponse,
    PaymentResponse,
    ReferralResponse,
    ServerBase,
    ServerResponse,
    ServerUpdate,
    TariffBase,
    TariffResponse,
    TariffUpdate,
    TemporaryDataResponse,
    TrackingSourceResponse,
    UserBase,
    UserResponse,
    UserUpdate,
)
from api.v1.schemas.keys import KeyBase, KeyCreateRequest, KeyUpdate
from api.v1.schemas.settings import SettingResponse, SettingUpsert
from api.v2.schemas.web import (
    WebBlockResponse,
    WebPageResponse,
    WebPageUpdate,
    WebPageVariantCreate,
    WebPageVariantSummary,
    WebPageVariantUpdate,
    WebPageVariantsResponse,
    WebTheme,
)
