BUTTON_ICON_CONFIG: dict[str, dict[str, str]] = {}

BACK = "⬅️ Назад"
APPLY = "✅ Подтвердить"
CANCEL = "❌ Отмена"

SUB_CHANELL = "📢 Подписаться"
SUB_CHANELL_DONE = "✅ Я подписался"

MAIN_MENU = "👤 Личный кабинет"
TRIAL_SUB = "🎁 Пробная подписка"
SUPPORT = "💬 Поддержка"
HAVE_PROBLEM = "🆘 У меня проблема"
NOT_HELPED = "❌ Не помогло"
CHANNEL = "📢 Канал"
ABOUT_VPN = "💬 О сервисе"
ADMIN_BTN = "📊 Администратор"

ADD_SUB = "Купить новую подписку"
MY_SUB = "🔐 Моя подписка"
MY_SUBS = "📱 Мои подписки"
BALANCE = "💵 Баланс"
WEB_CABINET = "🌐 Личный кабинет"
BIND_EMAIL = "📧 Привязать почту"
INVITE = "👥 Пригласить"
GIFTS = "🎁 Подарить"
INSTRUCTIONS = "📘 Инструкции"

CONNECT_DEVICE = "📲 Подключить устройство"
ROUTER_BUTTON = "Подключить роутер"
TV_BUTTON = "📺 Подключить Андроид TV"
RENEW_KEY = "⏳ Продлить подписку"
ADDONS_BUTTON_DEVICES = "➕ Добавить устройства"
ADDONS_BUTTON_TRAFFIC = "➕ Добавить трафик"
ADDONS_BUTTON_DEVICES_TRAFFIC = "➕ Добавить устройства/трафик"
HWID_BUTTON = "♻️ Сбросить привязку"
MY_DEVICES = "💻 Мои устройства"
UNBIND_DEVICE = "🔌 Отвязать"
QR = "📷 Показать QR-код"
DELETE = "❌ Удалить"
CHANGE_LOCATION = "🌍 Сменить локацию"
FREEZE = "Отключить подписку"
UNFREEZE = "Включить подписку"
ALIAS = "✏️"

TOP_FIVE = "🏆 Топ-5"

PAYMENT = "💳 Пополнить баланс"
BALANCE_HISTORY = "📊 Транзакции"
COUPON = "🎟️ Активировать купон"
COUPON_RESTART = "🎟️ Попробовать другой купон"

GIFT = "🎁 Подарить подписку"
MY_GIFTS = "🎁 Мои подарки"
GIFTS_MENU = "В меню подарков"
SHARE_GIFT = "🎁 Поделиться подарком"
GET_GIFT = "🎁 Получить подарок"
GIFT_CLAIM_NEW = "🆕 Новая подписка"
GIFT_CLAIM_EXTEND = "➕ Продлить: {label}"

PC_PC = "💻 Windows"
PC_MACOS = "🍏 macOS"
DOWNLOAD_PC_BUTTON = "💻 Скачать Windows"
DOWNLOAD_MACOS_BUTTON = "🍏 Скачать macOS"
CONNECT_WINDOWS_BUTTON = "💻 Подключить"
CONNECT_MACOS_BUTTON = "🍏 Подключить"
TV_CONTINUE = "▶ Продолжить"
TV_INSTRUCTIONS = "📖 Полная инструкция"

IPHONE = "🍏 Айфон"
ANDROID = "🤖 Андроид"
PC = "💻 Компьютер"
TV = "📺 Телевизор"
DOWNLOAD_IOS_BUTTON = "🍏 Скачать iOS"
DOWNLOAD_ANDROID_BUTTON = "🤖 Скачать Android"
IMPORT_IOS = "🍏 Подключить"
IMPORT_ANDROID = "🤖 Подключить"
MANUAL_INSTRUCTIONS = "📖 Ручная установка"

CONFIG_PAY_BUTTON_TEXT = "Оплатить {amount}"
CONFIRM_ADDON_BUTTON_TEXT = "Подтвердить доплату {amount}"
DOWNGRADE_ADDON_BUTTON_TEXT = "Понизить условия"
DOWNGRADE_CONFIRM_BUTTON_TEXT = "Подтвердить понижение"

YOOKASSA = "💳 ЮКасса: быстрая оплата"
YOOMONEY = "💳 ЮМани: перевод по карте"
FREEKASSA = "💰 FreeKassa: межд. платежи"
CRYPTOBOT = "💰 CryptoBot: криптовалюта"
STARS = "⭐ Оплата Звездами"
ROBOKASSA = "⭐ RoboKassa"
WATA_RU = "🇷🇺 WATA: Карты РФ / СБП"
WATA_INT = "🌍 WATA: Международные карты"
KASSAI = "💳 KassaAI"
KASSAI_CARDS = "💳 KassaAI: Карты РФ"
KASSAI_SBP = "🏦 KassaAI: СБП"
PARITYPAY_SBP = "🏦 ParityPay: СБП"
PLATEGA_SBP = "🏦 Platega: СБП"
PLATEGA_CARDS = "💳 Platega: Карты РФ"
PLATEGA_INT = "🌍 Platega: Международные карты"
PLATEGA_CRYPTO = "₿ Platega: Криптовалюта"
OVERPAY_CARDS = "💳 Оплата картой"
OVERPAY_SBP = "🏦 Оплата через СБП"
TRIBUTE = "💳 Tribute"
HELEKET = "Heleket Crypto"

PAY = "Пополнить"
PAY_2 = "Оплатить"
COMPLETE_PAYMENT = "Завершить оплату"
CUSTOM_AMOUNT = "💰 Ввести свою сумму"
STARS_BOT = "🤖 Бот для покупки звезд"
DONAT_BUTTON = "💰 Поддержать проект"

RUB_CURRENCY = "₽ Рубли (RUB)"
USD_CURRENCY = "$ USD / Cryptowallet"

TRIAL_BONUS = "🚀 Активировать пробный период"
RENEW_KEY_NOTIFICATION = "🔄 Продлить подписку"
CHANGE_TARIFF = "🔄 Сменить тариф"
DISCOUNT_TARIFF = "🔥 Получить скидку"
MAX_DISCOUNT_TARIFF = "⚡ Получить максимальную скидку"
