#!/bin/sh

echo "Сохранение текущих изменений..."
git stash -q --keep-index

echo "Запуск Ruff format..."
ruff format . --config pyproject.toml --exclude main.py,handlers/payments

echo "Запуск Ruff check с автоисправлением..."
ruff check . --config pyproject.toml --exclude main.py,handlers/payments --fix

git add -u

echo "Восстановление сохраненных изменений..."
git stash pop -q

exit 0 