DOWNLOAD_IOS_BUTTON = "🍏 Скачать для iOS"
DOWNLOAD_ANDROID_BUTTON = "🤖 Скачать для Android"
IMPORT_IOS = "🍏 Подключить на iOS"
IMPORT_ANDROID = "🤖 Подключить на Android"
PC_BUTTON = "💻 Компьютеры"
TV_BUTTON = "📺 Андроид TV"
