from typing import Final

from settings.texts import (
    ADMIN_GRANULAR_PERMISSIONS_HINT,
    EXPIRY_SKIP_TRIAL_HINT,
    MONEY_SETTINGS_DESCRIPTION,
    SINGLE_SUBSCRIPTION_SCREEN_HINT,
    TRAFFIC_SETTINGS_HINT,
    YOOKASSA_AUTOPAY_SETTINGS_DESCRIPTION,
    YOOKASSA_AUTOPAY_SETTING_HINTS,
    YOOKASSA_MARKUP_PERCENT_PROMPT,
    YOOKASSA_METHODS_HINT,
    YOOKASSA_SETTINGS_HINT,
)


SECTION_DESCRIPTIONS: Final[dict[str, str]] = {
    "payments": f"Какие платёжные системы доступны пользователям в боте и на сайте. {YOOKASSA_METHODS_HINT}",
    "money": MONEY_SETTINGS_DESCRIPTION,
    "buttons": "Какие кнопки видят пользователи в меню бота.",
    "notifications": "Автоматические уведомления, автопродление и интервалы фоновых задач.",
    "modes": "Режимы поведения бота.",
    "tariffs": "Правила смены тарифа и докупки опций.",
    "web": "Сайт и личный кабинет.",
    "remnawave": "Мониторинг панели Remnawave и автодействия с хостами.",
    "management": "Обслуживание и сервисные действия.",
    "yookassa": YOOKASSA_SETTINGS_HINT,
    "yookassa_autopay": YOOKASSA_AUTOPAY_SETTINGS_DESCRIPTION,
}

SETTING_HINTS: Final[dict[str, str]] = {
    **YOOKASSA_AUTOPAY_SETTING_HINTS,
    "KASSA2328": "Приём платежей через 2328. Настройте KASSA2328_PROJECT_UUID и KASSA2328_API_KEY на сервере.",
    "CHANNEL_BUTTON_ENABLE": "Кнопка перехода в ваш канал в меню бота",
    "DONATIONS_BUTTON_ENABLE": "Кнопка донатов в главном меню",
    "BALANCE_BUTTON_ENABLE": "Кнопка пополнения баланса в профиле",
    "REFERRAL_QR_BUTTON_ENABLE": "QR-код реферальной ссылки в реферальном меню",
    "DELETE_KEY_BUTTON_ENABLE": "Разрешить пользователю самому удалять подписку",
    "INSTRUCTIONS_BUTTON_ENABLE": "Кнопка инструкций по подключению",
    "GIFT_BUTTON_ENABLE": "Дарить подписки другим пользователям",
    "REFERRAL_BUTTON_ENABLE": "Реферальная программа в профиле",
    "TOP_REFERRAL_BUTTON_ENABLE": "Кнопка «Топ-5 рефереров»",
    "QRCODE_BUTTON_ENABLE": "QR-код подписки в карточке ключа",
    "HWID_RESET_BUTTON_ENABLE": "Кнопка сброса привязанных устройств",
    "ANDROID_TV_BUTTON_ENABLE": "Кнопка подключения Android TV",
    "COUPON_BUTTON_ENABLE": "Кнопка активации купона в профиле",
    "RENEW_ENABLED": "Автопродление подписок с баланса при истечении",
    "EXPIRY_24H_ENABLED": "Первое напоминание об истечении подписки",
    "EXPIRY_10H_ENABLED": "Второе напоминание ближе к истечению",
    "DELETE_KEY_ENABLED": "Удалять подписку спустя время после истечения",
    "RENEW_EXPIRED_ENABLED": "Пытаться продлить с баланса уже истёкшие подписки",
    "HOT_LEADS_ENABLED": "Напоминания тем, кто начал оплату и не завершил",
    "COLD_LEADS_ENABLED": "Прогрев зарегистрировавшихся без покупки",
    "RETURNING_ENABLED": "Возврат давно ушедших пользователей",
    "BASE_NOTIFICATION_MINUTE": "Период фонового цикла уведомлений, секунд",
    "INACTIVE_USER_ENABLED": "Часов неактивности до напоминания о пробнике",
    "EXPIRY_24H_BEFORE_HOURS": "За сколько часов слать первое напоминание",
    "EXPIRY_10H_BEFORE_HOURS": "За сколько часов слать второе напоминание",
    "DELETE_KEY_DELAY_MINUTES": "Задержка удаления после истечения, минут",
    "EXTRA_DAYS_AFTER_EXPIRY": "Бонусные дни к пробной подписке в напоминании",
    "INACTIVE_TRAFFIC_ENABLED": "Часов без трафика до уведомления",
    "HOT_LEADS_INTERVAL_HOURS": "Интервал напоминаний горячим лидам, часов",
    "COLD_LEADS_INTERVAL_HOURS": "Интервал сообщений холодным лидам, часов",
    "RETURNING_MIN_DAYS": "«Давно ушёл» — от скольких дней отсутствия",
    "RETURNING_MAX_DAYS": "«Давно ушёл» — до скольких дней отсутствия",
    "DISCOUNT_ACTIVE_HOURS": "Сколько часов действует скидочное предложение",
    "RENEW_BUTTON_BEFORE_DAYS": "За сколько дней до истечения доступно продление (бот и сайт)",
    "HWID_DELETE_PENALTY": "Штраф доверия за удаление устройства",
    "HWID_DAILY_RECOVERY": "Восстановление доверия за сутки",
    "HWID_MIN_TRUST_TO_DELETE": "Минимальное доверие для удаления устройства",
    "CAPTCHA_ENABLED": "Капча для новых пользователей при старте",
    "CHANNEL_CHECK_ENABLED": "Требовать подписку на канал для работы с ботом",
    "SHOW_START_MENU_ONLY_ONCE": "Стартовое меню только при первом /start",
    "INLINE_MODE_ENABLED": "Инлайн-режим (@бот в любом чате)",
    "RANDOM_SUBSCRIPTIONS_ENABLED": "Выдавать случайный сервер вместо выбора",
    "COUNTRY_SELECTION_ENABLED": "Пользователь выбирает страну при покупке",
    "REMNAWAVE_WEBAPP_ENABLED": "Кнопка подключения открывает подписку как WebApp",
    "REMNAWAVE_WEBAPP_OPEN_IN_BROWSER": "Ссылка подключения в браузере вместо WebApp",
    "HAPP_CRYPTOLINK_ENABLED": "Выдавать зашифрованные happ:// ссылки",
    "LEGACY_LINKS_ENABLED": "Старый формат ссылок подписки (совместимость)",
    "DIRECT_START_DISABLED": "Не отвечать на прямой /start — только по ссылкам",
    "TRIAL_TIME_DISABLED": "Полностью отключить пробный период",
    "WEB_TRIAL_DISABLED": "Скрыть пробный период только на сайте",
    "SUPPORT_TRIAGE_ENABLED": "Опросник перед обращением в поддержку",
    "SUPPORT_TICKETS_ENABLED": "Система тикетов: обращения на сайте и в отдельном боте поддержки",
    "SUPPORT_SHADOW_MODE": "Клиент просто пишет в бот поддержки: тикеты открываются и переоткрываются сами, без выбора категории и лишних уведомлений",
    "PROTECT_CONTENT_ENABLED": "Запрет пересылки и копирования сообщений бота",
    "TARIFF_OPTIONS_PAGINATION": "Опции тарифа слайдером вместо списка",
    "HWID_DELETE_COOLDOWN_ENABLED": "Кулдаун удаления устройств (система доверия)",
    "SINGLE_SUBSCRIPTION_MODE": "Не больше одной подписки на пользователя",
    "RENEWAL_CREDIT_AS_DAYS": "Остаток при смене тарифа переносить днями, а не деньгами",
    "RENEWAL_SWITCH_KEEP_PERIOD": "Смена тарифа без изменения срока: доплата только за оставшийся период (приоритетнее «Перерасчет дни»)",
    "GIFT_EXTEND_ENABLED": "Подарком можно продлить существующую подписку",
    "KEYWORD_REPLIES_ENABLED": "Отвечать на слова в чате: «купить» открывает тарифы, «старт» — меню",
    "FX_MARKUP": "Наценка к курсу при конвертации валют, %",
    "RUB_TO_USD": "Курс рубля к доллару для пересчёта цен",
    "CASHBACK": "Процент кэшбэка с платежей",
    "CURRENCY_MODE": "В какой валюте показывать цены пользователям",
    "ALLOW_DOWNGRADE": "Разрешить переход на более дешёвый тариф",
    "KEY_ADDONS_PACK_MODE": "Что можно докупать к активной подписке",
    "KEY_ADDONS_RECALC_PRICE": "Пересчитывать цену докупки по остатку срока",
    "KEY_ADDONS_CARRY_ON_RENEWAL": "Сохранять докупленные опции при продлении, включив их в цену",
    "WEB_ENABLED": "Показывать кнопку личного кабинета в боте",
    "SITE_URL": "Адрес сайта, с https://",
    "SITE_MODE": "Полный сайт с лендингом, только кабинет или только веб-апп в Telegram",
    "WEB_OPEN_IN_BROWSER": "Кабинет открывается в браузере, а не внутри Telegram",
    "WEBAPP_ONLY_TITLE": "Заголовок заглушки в браузере, когда включён режим «только веб-апп»",
    "WEBAPP_ONLY_TEXT": "Текст заглушки в браузере в режиме «только веб-апп»",
    "WEBAPP_ONLY_BUTTON": "Подпись кнопки на заглушке — ведёт в бота",
    "WEB_NODE_STATUS_INTERVAL_MIN": "Частота обновления блока «Статус серверов», минут",
    "EMAIL_BINDING_ENABLED": "Кнопка привязки email в боте — вход на сайт без Telegram",
    "EMAIL_BINDING_VERIFY_ENABLED": "Подтверждение почты кодом при привязке в боте. При недоступных SMTP/Redis почта сохраняется без подтверждения.",
    "EMAIL_BINDING_REMINDER_ENABLED": "Только Telegram WebApp; окно появляется не чаще заданного числа дней. Для привязки почты нужны настроенные SMTP и Redis.",
    "EMAIL_BINDING_REMINDER_INTERVAL_DAYS": "Число дней между показами: целое число от 1 до 365.",
    "WEB_NOTIFY_PAYMENT_TITLE": "Веб-уведомление об оплате. Переменная: {amount}",
    "WEB_NOTIFY_PAYMENT_MESSAGE": "Текст веб-уведомления об оплате. Переменная: {amount}",
    "WEB_NOTIFY_KEY_CREATED_TITLE": "Веб-уведомление о создании подписки. Переменная: {email}",
    "WEB_NOTIFY_KEY_CREATED_MESSAGE": "Текст уведомления о создании. Переменная: {email}",
    "WEB_NOTIFY_KEY_EXPIRY_TITLE": "Веб-уведомление об истечении. Переменная: {email}",
    "WEB_NOTIFY_KEY_EXPIRY_MESSAGE": "Текст уведомления об истечении. Переменная: {email}",
    "WEB_NOTIFY_KEY_EXPIRED_TITLE": "Веб-уведомление об истёкшей подписке. Переменная: {email}",
    "WEB_NOTIFY_KEY_EXPIRED_MESSAGE": "Текст уведомления об истёкшей подписке. Переменная: {email}",
    "WEB_NOTIFY_KEY_RENEWED_TITLE": "Веб-уведомление о продлении. Переменные: {email}, {expiry}",
    "WEB_NOTIFY_KEY_RENEWED_MESSAGE": "Текст уведомления о продлении. Переменные: {email}, {expiry}",
    "WEB_NOTIFY_GIFT_TITLE": "Веб-уведомление о подарке. Переменные: {name}, {duration}",
    "WEB_NOTIFY_GIFT_MESSAGE": "Текст уведомления о подарке. Переменные: {name}, {duration}",
    "EMAIL_LOGIN_SUBJECT": "Тема письма с кодом входа. Переменные: {project}, {code}",
    "EMAIL_LOGIN_BODY": "Текст письма с кодом входа. Переменная: {code}",
    "EMAIL_RESET_SUBJECT": "Тема письма сброса пароля. Переменные: {project}, {code}",
    "EMAIL_RESET_BODY": "Текст письма сброса пароля. Переменная: {code}",
    "EMAIL_LINK_SUBJECT": "Тема письма привязки email. Переменные: {project}, {code}",
    "EMAIL_LINK_BODY": "Текст письма привязки email. Переменная: {code}",
    "NODE_HEALTH_ENABLED": "Алерты админам о падении и восстановлении нод",
    "NODE_HEALTH_INTERVAL_MIN": "Период опроса панели, минут",
    "HOST_AUTO_DISABLE_ON_NODE_DOWN": "Автоматически выключать хосты упавшей ноды",
    "HOST_ROTATION_ENABLED": "Ротация хостов по расписанию",
    "HOST_ROTATION_INTERVAL_MIN": "Период ротации хостов, минут",
    "MAINTENANCE_ENABLED": "Бот отвечает заглушкой всем, кроме админов",
    "SINGLE_SUBSCRIPTION_OPEN_PROFILE": SINGLE_SUBSCRIPTION_SCREEN_HINT,
    "EXPIRY_24H_SKIP_TRIAL_ENABLED": EXPIRY_SKIP_TRIAL_HINT,
    "TRAFFIC_WARNING_ENABLED": TRAFFIC_SETTINGS_HINT,
    "TRAFFIC_WARNING_LEVEL_1_ENABLED": TRAFFIC_SETTINGS_HINT,
    "TRAFFIC_WARNING_LEVEL_2_ENABLED": TRAFFIC_SETTINGS_HINT,
    "TRAFFIC_WARNING_LEVEL_1_PERCENT": TRAFFIC_SETTINGS_HINT,
    "TRAFFIC_WARNING_LEVEL_2_PERCENT": TRAFFIC_SETTINGS_HINT,
    "TRAFFIC_EXHAUSTED_ENABLED": TRAFFIC_SETTINGS_HINT,
    "ADMIN_GRANULAR_PERMISSIONS_ENABLED": ADMIN_GRANULAR_PERMISSIONS_HINT,
    "MARKUP_ENABLED": YOOKASSA_SETTINGS_HINT,
    "MARKUP_PERCENT": YOOKASSA_MARKUP_PERCENT_PROMPT,
    "YOOKASSA": YOOKASSA_METHODS_HINT,
    "YOOKASSA_SBP": YOOKASSA_METHODS_HINT,
}
