import type { ElementDefinition, ElementVisualDefinition } from "@/components/constructor/elementDefinitions";
import { PANEL_PRESENTATION_CAPABILITY } from "@/components/constructor/presentation/elementCapabilityCatalog";
import { createLazyView } from "@/components/constructor/blockContent/lazyViews";

const DefaultGiftCtaBlockView = createLazyView(() => import("../blockContent/DefaultGiftCtaBlockView").then(m => ({ default: m.DefaultGiftCtaBlockView })));
const DefaultGiftRedeemBlockView = createLazyView(() => import("../blockContent/DefaultGiftRedeemBlockView").then(m => ({ default: m.DefaultGiftRedeemBlockView })));
const DefaultGiftCardsGridBlockView = createLazyView(() => import("../blockContent/DefaultGiftCardsGridBlockView").then(m => ({ default: m.DefaultGiftCardsGridBlockView })));
const DefaultPromoActivateBlockView = createLazyView(() => import("../blockContent/DefaultPromoActivateBlockView").then(m => ({ default: m.DefaultPromoActivateBlockView })));
const DefaultBalanceTopUpBlockView = createLazyView(() => import("../blockContent/DefaultBalanceTopUpBlockView").then(m => ({ default: m.DefaultBalanceTopUpBlockView })));
const DefaultGiftHistoryBlockView = createLazyView(() => import("../blockContent/DefaultGiftHistoryBlockView").then(m => ({ default: m.DefaultGiftHistoryBlockView })));
const DefaultDailyBonusBlockView = createLazyView(() => import("../blockContent/dailyBonus/DefaultDailyBonusBlockView").then(m => ({ default: m.DefaultDailyBonusBlockView })));

const BASE_GRID = { col: 0, row: 0, zIndex: 0, fontScale: 1 };
const PACK = "default";
const MONO_FONT = "";

const PANEL_VISUAL: ElementVisualDefinition = {
  textLike: false,
  cardCollection: false,
  autoTextScale: "none",
  hoverTarget: "control",
  outlineTarget: "surface",
  glowTarget: "surface",
  shadowTarget: "surface",
  disableAutoHoverWhenUnconfigured: true,
  overflowVisibleInGrid: true,
};

/** Бонусы, подарки и промокоды. */
export const DEFAULT_BONUS_BLOCKS: ElementDefinition[] = [
  {
    type: "defaultDailyBonus",
    label: "Стандарт: ежедневный бонус",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 9,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "Ежедневный бонус",
      panelHeaderHintFmt: "серия {streak}",
      introText: "Забирай бонус на баланс каждый день — чем дольше серия, тем больше сумма.",
      amountFmt: "{amount} ₽",
      amountRangeFmt: "{min}–{max} ₽",
      claimLabel: "Забрать бонус",
      claimingLabel: "Начисляем...",
      successFmt: "✓ Начислено {amount} ₽",
      errorText: "✕ Не удалось начислить бонус",
      loadingText: "Загрузка...",
      waitLabel: "Следующий бонус через",
      countdownFmt: "{hh}:{mm}:{ss}",
      reasonCooldownText: "Бонус на сегодня уже получен",
      reasonLimitText: "Лимит бонусов за период исчерпан",
      reasonSubscriptionText: "Бонус доступен с активной подпиской",
      reasonAccountAgeText: "Бонус откроется чуть позже после регистрации",
      reasonDisabledText: "Ежедневный бонус сейчас недоступен",
      showStreak: true,
      showLadder: true,
      ladderTitle: "Серия",
      ladderDayFmt: "{days} д",
      ladderMaxItems: 7,
      showTotal: true,
      totalFmt: "всего получено {total} ₽",
      showClaimsLeft: true,
      claimsLeftFmt: "осталось бонусов: {left}",
      backendVisibilityKey: "dailyBonusEnabled",
      respectBackendVisibility: true,
    },
    view: DefaultDailyBonusBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 9, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultDailyBonus",
        category: "cabinet",
        label: "Ежедневный бонус",
        description: "Кнопка «Забрать бонус», серия и таймер до следующего. Суммы и кулдаун — в настройках бота, раздел «Бонусы».",
        cabinetTabHints: ["profile"],
        priority: 12,
      },
    ],
  },
  {
    type: "defaultGiftCta",
    label: "Стандарт: подарить (CTA)",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 5,
      monoFontFamily: MONO_FONT,
      panelHint: "Подари подписку",
      title: "Подарить подписку",
      titleAccent: "",
      description: "Выберите тариф — получатель активирует код в один клик. Работает для любого нового аккаунта.",
      ctaLabel: "Выбрать подарок",
      groupCode: "gifts",
      checkoutSlug: "checkout",
      emptyText: "Нет доступных тарифов",
      loadingText: "Загрузка тарифов...",
      errorText: "Не удалось загрузить тарифы",
      pickLabel: "Подарить →",
      backLabel: "← Назад",
      perDayLabel: "в день",
      unlimitedText: "∞",
      perPage: 5,
      prevLabel: "← Пред",
      nextLabel: "След →",
      pageFormat: "{page} / {total}",
    },
    view: DefaultGiftCtaBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultGiftCta",
        category: "cabinet",
        label: "Стандарт: подарить подписку (CTA)",
        description: "Призывная карточка с кнопкой «Выбрать подарок», открывает inline-список тарифов.",
        cabinetTabHints: ["gifts"],
        priority: 5,
      },
    ],
  },
  {
    type: "defaultGiftCardsGrid",
    label: "Стандарт: подарки-карточки",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 14,
      monoFontFamily: MONO_FONT,
      source: "tariffs",
      tariffsGroupCode: "",
      tariffCheckoutSlug: "checkout",
      tariffCtaLabel: "Подарить",
      tariffTagLabel: "Тариф",
      tariffLoadingText: "Загрузка тарифов...",
      tariffEmptyText: "Нет доступных тарифов",
      tariffPeriodFmt: "{days} дн",
      tariffDevicesFmt: "{n} устр.",
      tariffTrafficFmt: "{n} ГБ",
      tariffUnlimitedText: "∞",
      cards: [],
    },
    view: DefaultGiftCardsGridBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultGiftCardsGrid",
        category: "cabinet",
        label: "Стандарт: подарки-карточки",
        description: "Сетка из 3 карточек подарков/промо со статусом и кнопкой действия.",
      },
    ],
  },
  {
    type: "defaultPromoActivate",
    label: "Стандарт: активация промокода",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 4,
      monoFontFamily: MONO_FONT,
      panelHeader: "Активировать промокод",
      panelHeaderHint: "",
      placeholder: "PROMO-XXXX-XXXX",
      submitLabel: "Активировать",
      submittingLabel: "Активируем...",
      successText: "✓ Промокод применён",
      errorText: "✕ Неверный или истёкший код",
    },
    view: DefaultPromoActivateBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 4, data: {} },
    insert: [
      {
        key: "defaultPromoActivate",
        category: "cabinet",
        label: "Стандарт: активация промокода",
        description: "Поле ввода промокода с подтверждением через POST /api/coupons/apply. Подходит и для активации подарочных кодов.",
        cabinetTabHints: ["gifts"],
      },
    ],
  },
  {
    type: "defaultBalanceTopUp",
    label: "Стандарт: пополнение баланса",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 5,
      monoFontFamily: MONO_FONT,
      panelHeader: "Пополнить баланс",
      panelHeaderHint: "Выберите или введите сумму",
      amountPlaceholder: "500",
      submitLabel: "Пополнить",
      presetAmounts: [100, 300, 500, 1000],
      minAmount: 50,
    },
    view: DefaultBalanceTopUpBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 14, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultBalanceTopUp",
        category: "cabinet",
        label: "Стандарт: пополнение баланса",
        description: "Ввод суммы и переход на страницу оплаты (flow=balance) с выбором кассы. Стиль набора «Стандарт».",
        cabinetTabHints: ["profile", "keys"],
      },
    ],
  },
  {
    type: "defaultGiftRedeem",
    label: "Стандарт: активация подарка",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 4,
      monoFontFamily: MONO_FONT,
      panelHeader: "Активировать подарок",
      panelHeaderHint: "",
      description: "Введите код подарка от другого пользователя — после активации новый ключ появится в вашем кабинете.",
      placeholder: "Ссылка или код подарка",
      submitLabel: "Активировать",
      submittingLabel: "Активируем...",
      successText: "✓ Подарок активирован",
      notFoundText: "✕ Код не найден или уже использован",
      errorText: "✕ Не удалось активировать",
      invalidFormatText: "✕ Только латинские буквы, цифры, дефис",
      minLength: 3,
    },
    view: DefaultGiftRedeemBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 14, rowSpan: 4, data: {} },
    insert: [
      {
        key: "defaultGiftRedeem",
        category: "cabinet",
        label: "Стандарт: активация подарка",
        description: "Поле ввода подарочного кода (от другого юзера) — POST /api/gifts/redeem. Отдельно от промокода.",
        cabinetTabHints: ["gifts"],
        priority: 10,
      },
    ],
  },
  {
    type: "defaultGiftHistory",
    label: "Стандарт: история подарков",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "История",
      panelHeaderHintFormat: "активировано {used} из {total}",
      emptyText: "Пока нет подарков",
      loadingText: "Загрузка...",
      unauthenticatedText: "Войдите в аккаунт",
      unusedLabel: "Ожидает",
      usedLabel: "Использован",
      maxItems: 100,
    },
    view: DefaultGiftHistoryBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultGiftHistory",
        category: "cabinet",
        label: "Стандарт: история подарков",
        description: "Список оформленных подарков из useMyGifts() со статусом.",
      },
    ],
  },
];
