import type { ElementDefinition, ElementVisualDefinition } from "@/components/constructor/elementDefinitions";
import { PANEL_PRESENTATION_CAPABILITY } from "@/components/constructor/presentation/elementCapabilityCatalog";
import { createLazyView } from "@/components/constructor/blockContent/lazyViews";
import { DEFAULT_APP_STEPS, appCatalogSeed, appStepsSeed } from "@/components/constructor/blockContent/appCatalog";

const DefaultSectionTabsBlockView = createLazyView(() => import("../blockContent/DefaultSectionTabsBlockView").then(m => ({ default: m.DefaultSectionTabsBlockView })));
const DefaultHapticSettingsBlockView = createLazyView(() => import("../blockContent/DefaultHapticSettingsBlockView").then(m => ({ default: m.DefaultHapticSettingsBlockView })));
const DefaultChangePasswordBlockView = createLazyView(() => import("../blockContent/DefaultChangePasswordBlockView").then(m => ({ default: m.DefaultChangePasswordBlockView })));
const DefaultThemeModeBlockView = createLazyView(() => import("../blockContent/DefaultThemeModeBlockView").then(m => ({ default: m.DefaultThemeModeBlockView })));
const DefaultPwaInstallBlockView = createLazyView(() => import("../blockContent/DefaultPwaInstallBlockView").then(m => ({ default: m.DefaultPwaInstallBlockView })));
const DefaultPushPermissionBlockView = createLazyView(() => import("../blockContent/DefaultPushPermissionBlockView").then(m => ({ default: m.DefaultPushPermissionBlockView })));
const DefaultDeviceListBlockView = createLazyView(() => import("../blockContent/DefaultDeviceListBlockView").then(m => ({ default: m.DefaultDeviceListBlockView })));
const DefaultAppDownloadBlockView = createLazyView(() => import("../blockContent/DefaultAppDownloadBlockView").then(m => ({ default: m.DefaultAppDownloadBlockView })));
const DefaultQuickActionsBlockView = createLazyView(() => import("../blockContent/DefaultQuickActionsBlockView").then(m => ({ default: m.DefaultQuickActionsBlockView })));

const BASE_GRID = { col: 0, row: 0, zIndex: 0, fontScale: 1 };
const PACK = "default";
const MONO_FONT = "";

const PANEL_VISUAL: ElementVisualDefinition = {
  textLike: false,
  cardCollection: false,
  autoTextScale: "none",
  hoverTarget: "control",
  outlineTarget: "surface",
  glowTarget: "surface",
  shadowTarget: "surface",
  disableAutoHoverWhenUnconfigured: true,
  overflowVisibleInGrid: true,
};

/** Кабинет: настройки, устройства и приложения. */
export const DEFAULT_CABINET_SETTINGS_BLOCKS: ElementDefinition[] = [
  {
    type: "defaultQuickActions",
    label: "Стандарт: быстрые действия",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 18,
      rowSpan: 5,
      monoFontFamily: MONO_FONT,
      panelHeader: "Быстрые действия",
      panelHeaderHint: "",
      emptyText: "Действия не настроены",
      maxColumns: 3,
      items: [
        { icon: "🔑", title: "Моя подписка", subtitle: "Тариф, продление, ключ", linkType: "tab", cabinetTabId: "keys" },
        { icon: "⬇️", title: "Установка", subtitle: "Приложение и настройка", linkType: "tab", cabinetTabId: "instructions" },
        { icon: "🎁", title: "Подарки", subtitle: "Промокоды и сертификаты", linkType: "tab", cabinetTabId: "gifts" },
      ],
    },
    view: DefaultQuickActionsBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultQuickActions",
        category: "cabinet",
        label: "Стандарт: быстрые действия",
        description: "Карточки-кнопки: каждая ведёт на вкладку кабинета или ссылку. Набор задаёт админ.",
        cabinetTabHints: ["profile", "keys"],
      },
    ],
  },
  {
    type: "defaultSectionTabs",
    roles: ["sectionTabs"],
    label: "Стандарт: табы раздела",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 1,
      monoFontFamily: MONO_FONT,
      tabsGroup: "section",
      defaultScreenId: "main",
      displayMode: "text",
      orientation: "horizontal",
      tabs: [],
    },
    view: DefaultSectionTabsBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: true,
    inspector: { showGenericHoverControls: false },
    visual: { ...PANEL_VISUAL, overflowVisibleInGrid: true },
    preview: { colSpan: 12, rowSpan: 1, data: {} },
    insert: [
      {
        key: "defaultSectionTabs",
        category: "cabinet",
        label: "Стандарт: табы раздела",
        description: "Горизонтальные моно-табы для переключения экранов раздела.",
      },
    ],
  },
  {
    type: "defaultHapticSettings",
    label: "Стандарт: сила вибрации",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 12,
      rowSpan: 2,
      monoFontFamily: MONO_FONT,
      panelHeader: "Вибрация",
      hint: "отклик",
      offLabel: "Выкл",
      lightLabel: "Слабый",
      mediumLabel: "Средний",
      heavyLabel: "Сильный",
      unsupportedLabel: "Устройство не поддерживает вибрацию — отклик будет только в приложении Telegram.",
    },
    view: DefaultHapticSettingsBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: true,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 2, data: {} },
    insert: [
      {
        key: "defaultHapticSettings",
        category: "cabinet",
        label: "Стандарт: сила вибрации",
        description: "Клиент сам выбирает силу хаптика (выкл/слабый/средний/сильный). Выбор хранится у него.",
      },
    ],
  },
  {
    type: "defaultChangePassword",
    label: "Стандарт: смена пароля",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 12,
      rowSpan: 5,
      monoFontFamily: MONO_FONT,
      panelHeader: "Смена пароля",
      hint: "",
      currentLabel: "Текущий пароль",
      newLabel: "Новый пароль",
      confirmLabel: "Повторите новый пароль",
      submitLabel: "Сменить пароль",
    },
    view: DefaultChangePasswordBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: true,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultChangePassword",
        category: "cabinet",
        label: "Стандарт: смена пароля",
        description: "Форма смены пароля: текущий, новый и подтверждение. Меняет пароль аккаунта.",
      },
    ],
  },
  {
    type: "defaultThemeMode",
    label: "Стандарт: переключатель темы",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 12,
      rowSpan: 2,
      monoFontFamily: MONO_FONT,
      panelHeader: "Тема",
      hint: "вид",
      lightLabel: "Светлая",
      darkLabel: "Тёмная",
      autoLabel: "Системная",
    },
    view: DefaultThemeModeBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: true,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 2, data: {} },
    insert: [
      {
        key: "defaultThemeMode",
        category: "cabinet",
        label: "Стандарт: переключатель темы",
        description: "Клиент выбирает светлую, тёмную или системную тему. Выбор хранится у него.",
      },
    ],
  },
  {
    type: "defaultPwaInstall",
    label: "Стандарт: установка приложения",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 12,
      rowSpan: 3,
      monoFontFamily: MONO_FONT,
      panelHeader: "Приложение",
      hint: "PWA",
      description: "Установи кабинет как приложение — быстрый доступ с домашнего экрана, без браузера.",
      installLabel: "Установить приложение",
      installedLabel: "Приложение установлено",
      unavailableLabel: "Установка недоступна в этом браузере",
    },
    view: DefaultPwaInstallBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: true,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 3, data: {} },
    insert: [
      {
        key: "defaultPwaInstall",
        category: "cabinet",
        label: "Стандарт: установка приложения",
        description: "Кнопка установки кабинета как PWA (домашний экран). Сама определяет доступность.",
      },
    ],
  },
  {
    type: "defaultPushPermission",
    label: "Стандарт: разрешения уведомлений",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 12,
      rowSpan: 3,
      monoFontFamily: MONO_FONT,
      panelHeader: "Уведомления",
      hint: "доступ",
      description: "Разреши push-уведомления, чтобы не пропустить окончание подписки, оплаты и важные события.",
      enableLabel: "Разрешить уведомления",
      grantedLabel: "Уведомления разрешены",
      deniedLabel: "Уведомления заблокированы в настройках браузера",
      unsupportedLabel: "Уведомления не поддерживаются в этом браузере",
      subscribeErrorLabel: "Разрешение получено, но подписку не удалось сохранить. Попробуйте ещё раз.",
    },
    view: DefaultPushPermissionBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: true,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 3, data: {} },
    insert: [
      {
        key: "defaultPushPermission",
        category: "cabinet",
        label: "Стандарт: разрешения уведомлений",
        description: "Запрос разрешения на push-уведомления браузера + подписка.",
      },
    ],
  },
  {
    type: "defaultDeviceList",
    label: "Стандарт: подключённые устройства",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 8,
      monoFontFamily: MONO_FONT,
      panelHeader: "Устройства",
      hintFormat: "{count} / {limit}",
      emptyText: "Нет подключённых устройств",
      errorText: "Не удалось загрузить устройства",
      loadingText: "Загрузка...",
      noKeysText: "Нет активной подписки",
      deleteLabel: "Отвязать",
      deleteBusyLabel: "…",
      deleteSuccessText: "Устройство отвязано",
      deleteErrorText: "Не удалось отвязать устройство",
      pageSize: 4,
    },
    view: DefaultDeviceListBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultDeviceList",
        category: "cabinet",
        label: "Стандарт: подключённые устройства",
        description: "Список HWID-устройств подписки: модель, платформа, дата + отвязка отдельного устройства. Пагинация.",
      },
    ],
  },
  {
    type: "defaultAppDownload",
    label: "Стандарт: установка приложения",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 8,
      monoFontFamily: MONO_FONT,
      viewMode: "steps",
      panelHeader: "Установка приложения",
      hint: "",
      platformTitle: "Выберите устройство",
      clientTitle: "Выберите приложение",
      stepsTitle: "Что делать",
      downloadLabel: "Скачать",
      installLabel: "Установить {app}",
      backLabel: "Назад",
      restartLabel: "Выбрать другое приложение",
      counterFormat: "Шаг {n} из {total}",
      noClientsText: "Для этой платформы приложений пока нет",
      noStepsText: "Инструкция появится после выбора приложения",
      labelIos: "iPhone / iPad",
      labelAndroid: "Android",
      labelWindows: "Windows",
      labelMacos: "macOS",
      labelLinux: "Linux",
      showSteps: true,
      showDownload: true,
      apps: appCatalogSeed(),
      steps: appStepsSeed(DEFAULT_APP_STEPS),
    },
    view: DefaultAppDownloadBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultAppDownload",
        category: "cabinet",
        label: "Стандарт: установка приложения",
        description: "Установка клиента: два вида — пошаговый мастер или всё сразу. Платформы, приложения и шаги редактируются.",
        cabinetTabHints: ["keys", "instructions"],
      },
    ],
  },
];
