import type { ElementDefinition, ElementVisualDefinition } from "@/components/constructor/elementDefinitions";
import { PANEL_PRESENTATION_CAPABILITY } from "@/components/constructor/presentation/elementCapabilityCatalog";
import { createLazyView } from "@/components/constructor/blockContent/lazyViews";

const DefaultStatStripBlockView = createLazyView(() => import("../blockContent/DefaultStatStripBlockView").then(m => ({ default: m.DefaultStatStripBlockView })));
const DefaultProfileCardBlockView = createLazyView(() => import("../blockContent/DefaultProfileCardBlockView").then(m => ({ default: m.DefaultProfileCardBlockView })));
const DefaultSecurityPanelBlockView = createLazyView(() => import("../blockContent/DefaultSecurityPanelBlockView").then(m => ({ default: m.DefaultSecurityPanelBlockView })));
const DefaultLoginHistoryBlockView = createLazyView(() => import("../blockContent/DefaultLoginHistoryBlockView").then(m => ({ default: m.DefaultLoginHistoryBlockView })));
const DefaultTrafficUsageBlockView = createLazyView(() => import("../blockContent/DefaultTrafficUsageBlockView").then(m => ({ default: m.DefaultTrafficUsageBlockView })));
const DefaultUsageRingsBlockView = createLazyView(() => import("../blockContent/DefaultUsageRingsBlockView").then(m => ({ default: m.DefaultUsageRingsBlockView })));
const DefaultAdminToolsBlockView = createLazyView(() => import("../blockContent/DefaultAdminToolsBlockView").then(m => ({ default: m.DefaultAdminToolsBlockView })));
const DefaultTrafficTrendBlockView = createLazyView(() => import("../blockContent/DefaultTrafficTrendBlockView").then(m => ({ default: m.DefaultTrafficTrendBlockView })));
const DefaultNodeStatusBlockView = createLazyView(() => import("../blockContent/DefaultNodeStatusBlockView").then(m => ({ default: m.DefaultNodeStatusBlockView })));

const BASE_GRID = { col: 0, row: 0, zIndex: 0, fontScale: 1 };
const PACK = "default";
const MONO_FONT = "";

const PANEL_VISUAL: ElementVisualDefinition = {
  textLike: false,
  cardCollection: false,
  autoTextScale: "none",
  hoverTarget: "control",
  outlineTarget: "surface",
  glowTarget: "surface",
  shadowTarget: "surface",
  disableAutoHoverWhenUnconfigured: true,
  overflowVisibleInGrid: true,
};

/** Кабинет: профиль, статистика и безопасность. */
export const DEFAULT_CABINET_PROFILE_BLOCKS: ElementDefinition[] = [
  {
    type: "defaultTrafficUsage",
    label: "Стандарт: трафик",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 2,
      monoFontFamily: MONO_FONT,
      panelHeader: "Трафик",
      usedFormat: "{used} / {limit} ГБ",
      remainingFormat: "Осталось {left} ГБ",
      unlimitedText: "Безлимитный трафик",
      unlimitedHint: "∞",
      noKeysText: "Нет активной подписки",
      loadingText: "Загрузка...",
      lowWarnPercent: 90,
    },
    view: DefaultTrafficUsageBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 2, data: {} },
    insert: [
      {
        key: "defaultTrafficUsage",
        category: "cabinet",
        label: "Стандарт: трафик",
        description: "Расход трафика активной подписки: прогресс-бар «использовано / лимит ГБ» + остаток. На безлимите показывает ∞.",
      },
    ],
  },
  {
    type: "defaultUsageRings",
    label: "Стандарт: трафик и устройства",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 11,
      monoFontFamily: MONO_FONT,
      panelHeader: "Трафик и устройства",
      trafficLabel: "Трафик",
      trafficUnitFormat: "из {limit} ГБ",
      trafficUnlimitedText: "Безлимит",
      devicesLabel: "Устройства",
      devicesSubLabel: "подключено",
      devicesUnlimitedText: "∞",
      unitGb: "ГБ",
      devicesListTitle: "Подключённые устройства",
      emptyDevicesText: "Нет подключённых устройств",
      deleteLabel: "Отвязать",
      deleteBusyLabel: "…",
      deleteSuccessText: "Устройство отвязано",
      deleteErrorText: "Не удалось отвязать устройство",
      noKeysText: "Нет активной подписки",
      loadingText: "Загрузка...",
      lowWarnPercent: 90,
      pageSize: 3,
    },
    view: DefaultUsageRingsBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 11, data: {} },
    insert: [
      {
        key: "defaultUsageRings",
        category: "cabinet",
        label: "Стандарт: трафик и устройства",
        description: "Одна карточка: два кольцевых графика (трафик % и устройства подключено/лимит) + список устройств с отвязкой. Безлимит → ∞.",
      },
    ],
  },
  {
    type: "defaultAdminTools",
    label: "Стандарт: админ-инструменты",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 3,
      monoFontFamily: MONO_FONT,
      panelHeader: "Администратор",
      adminPanelLabel: "Веб-админка",
      adminPanelHref: "/admin",
      hint: "Видно только администраторам сайта",
      analyticsLabel: "Аналитика",
      logsLabel: "Логи и здоровье",
      auditLabel: "Журнал действий",
    },
    view: DefaultAdminToolsBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 3, data: {} },
    insert: [
      {
        key: "defaultAdminTools",
        category: "cabinet",
        label: "Стандарт: админ-инструменты",
        description: "Кнопки «Аналитика» и «Логи и здоровье» — открывают админ-панели. Виден только администраторам (cookie is_admin), у остальных скрыт.",
      },
    ],
  },
  {
    type: "defaultTrafficTrend",
    label: "Стандарт: график трафика",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 4,
      monoFontFamily: MONO_FONT,
      panelHeader: "Использование трафика",
      emptyText: "Данные появятся в течение нескольких дней.",
      unitLabel: "ГБ",
      peakLabel: "Пик",
      lastLabel: "Сейчас",
    },
    view: DefaultTrafficTrendBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 4, data: {} },
    insert: [
      {
        key: "defaultTrafficTrend",
        category: "cabinet",
        label: "Стандарт: график трафика",
        description: "График использования трафика по дням (накапливается ежедневным снапшотом). Данные появляются за несколько дней.",
      },
    ],
  },
  {
    type: "defaultStatStrip",
    label: "Стандарт: метрики 4×",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 3,
      monoFontFamily: MONO_FONT,
      tiles: [
        { metric: "balance", label: "Баланс" },
        { metric: "keysTotal", label: "Подписки" },
        { metric: "referralsTotal", label: "Рефералы" },
        { metric: "referralBonusTotal", label: "Бонус" },
      ],
    },
    view: DefaultStatStripBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 24, rowSpan: 3, data: {} },
    insert: [
      {
        key: "defaultStatStrip",
        category: "cabinet",
        label: "Стандарт: метрики 4× (общие)",
        description: "Полоса из 4 метрик: баланс, подписки, рефералы, бонус.",
      },
      {
        key: "defaultStatStripSubscription",
        category: "cabinet",
        label: "Подписки: метрики 4×",
        description: "Метрики активной подписки: устройств, трафик, дней до окончания, цена продления.",
        data: {
          tiles: [
            { metric: "subscriptionDevices" },
            { metric: "subscriptionTraffic" },
            { metric: "subscriptionDaysLeft" },
            { metric: "subscriptionRenewalPrice" },
          ],
        },
      },
      {
        key: "defaultStatStripReferrals",
        category: "cabinet",
        label: "Рефералка: метрики 4×",
        description: "Метрики реферальной программы: приведено, активных, бонус, конверсия.",
        data: {
          tiles: [
            { metric: "referralsTotal", label: "Приведено" },
            { metric: "referralsActive", label: "Активных" },
            { metric: "referralBonusTotal", label: "Бонус" },
            { metric: "referralConversion", label: "Конверсия" },
          ],
        },
      },
      {
        key: "defaultStatStripPartner",
        category: "cabinet",
        label: "Партнёрка: метрики 4×",
        description: "Метрики партнёрской программы: приведено, оплатили, кэшбек, конверсия.",
        data: {
          tiles: [
            { metric: "partnerReferredTotal", label: "Приведено" },
            { metric: "partnerReferredPaid", label: "Оплатили" },
            { metric: "partnerBalance", label: "Кэшбек" },
            { metric: "partnerConversion", label: "Конверсия" },
          ],
        },
      },
    ],
  },
  {
    type: "defaultProfileCard",
    label: "Стандарт: профиль",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 7,
      monoFontFamily: MONO_FONT,
      showAvatar: true,
      showJoinedSince: true,
      joinedPrefix: "с",
      joinedSincePrefix: "С нами",
      daysSinceSuffix: "дн",
      verifiedBadgeText: "Подтверждён",
      loadingText: "Загрузка...",
      emptyAuthText: "Войдите в аккаунт",
      bindLabel: "Привязать",
      bindEmailHref: "",
      bindTelegramHref: "",
      fields: [
        { kind: "email", label: "E-mail", showVerifiedBadge: true },
        { kind: "telegram", label: "Telegram", showVerifiedBadge: true },
        { kind: "identity", label: "ID" },
        { kind: "language", label: "Язык", value: "Русский" },
      ],
    },
    view: DefaultProfileCardBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 7, data: {} },
    insert: [
      {
        key: "defaultProfileCard",
        category: "cabinet",
        label: "Стандарт: профиль",
        description: "Карточка профиля с аватаром, датой регистрации и ключевыми полями. Тянется из /api/auth/summary.",
      },
    ],
  },
  {
    type: "defaultSecurityPanel",
    label: "Стандарт: безопасность",
    pack: PACK,
    defaultData: {
      panelHeader: "Безопасность",
      panelHeaderHint: "",
      sessionsLabel: "Активные сессии",
      sessionsDesc: "Сколько устройств вошли в аккаунт прямо сейчас.",
      revokeOthersLabel: "Завершить другие",
      revokeBusyLabel: "Завершаем...",
      revokeOnlyLabel: "Только это устройство",
      revokeOkText: "Другие сессии завершены",
      revokeErrorText: "Не удалось завершить сессии",
      passwordLabel: "Пароль",
      passwordSetDesc: "Установлен. Можно сменить в любой момент.",
      passwordEmptyDesc: "Не установлен. Войти можно только через почту или Telegram.",
      changePasswordLabel: "Сменить",
      setPasswordLabel: "Установить",
      passwordHref: "/forgot-password",
      bindingsLabel: "Привязки",
      bindingsDescFmt: "Почта: {email} · Telegram: {tg}",
      bindingsManageLabel: "Управлять",
      bindingsHref: "#bind-account",
      presentLabel: "✓",
      absentLabel: "—",
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 8,
      monoFontFamily: MONO_FONT,
    },
    view: DefaultSecurityPanelBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 8, data: {} },
    insert: [
      {
        key: "defaultSecurityPanel",
        category: "cabinet",
        label: "Стандарт: безопасность",
        description: "Безопасность аккаунта: активные сессии с завершением чужих, состояние пароля и привязок.",
      },
    ],
  },
  {
    type: "defaultLoginHistory",
    label: "Стандарт: история входов",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "История входов",
      allLabel: "Все сессии",
      allHref: "",
      emptyText: "История пуста",
      loadingText: "Загрузка...",
      unauthenticatedText: "Войдите в аккаунт",
      currentSuffix: "сейчас",
      revokeLabel: "Завершить",
      maxItems: 100,
    },
    view: DefaultLoginHistoryBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultLoginHistory",
        category: "cabinet",
        label: "Стандарт: история входов",
        description: "Список сессий пользователя из identity_sessions API с возможностью завершить чужую сессию.",
      },
    ],
  },
  {
    type: "defaultNodeStatus",
    label: "Стандарт: статус серверов",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 9,
      monoFontFamily: MONO_FONT,
      panelHeader: "Статус серверов",
      hint: "",
      onlineLabel: "Работает",
      offlineLabel: "Не работает",
      checkingLabel: "Проверка…",
      pingFormat: "≈ {ms} мс",
      fastestFormat: "⚡ Самый быстрый: {name} · ≈ {ms} мс",
      recommendFormat: "🚀 Рекомендуем: {name} (меньше всего нагрузка)",
      probePort: 8443,
      probeEnabled: true,
      emptyText: "Нет данных о серверах",
      loadingText: "Загрузка…",
      totalFormat: "Всего {total} · онлайн {online} · недоступно {offline}",
      pageSize: 6,
      prevLabel: "Назад",
      nextLabel: "Вперёд",
      items: [],
    },
    view: DefaultNodeStatusBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultNodeStatus",
        category: "cabinet",
        label: "Стандарт: статус серверов",
        description: "Показывает клиенту, какие ноды работают/недоступны. Выключенные вручную скрыты. Ярлыки настраиваются в редакторе.",
        cabinetTabHints: ["keys"],
      },
    ],
  },
];
