import type { ElementDefinition, ElementVisualDefinition } from "@/components/constructor/elementDefinitions";
import { PANEL_PRESENTATION_CAPABILITY, FORM_PRESENTATION_CAPABILITY } from "@/components/constructor/presentation/elementCapabilityCatalog";
import { GRID_COLUMNS } from "@/components/constructor/gridConstants";
import { DefaultLoginFormBlockView } from "../blockContent/DefaultLoginFormBlockView";
import { DefaultCheckoutBlockView } from "../blockContent/DefaultCheckoutBlockView";
import { DefaultCheckoutBannerBlockView } from "../blockContent/DefaultCheckoutBannerBlockView";

const BASE_GRID = { col: 0, row: 0, zIndex: 0, fontScale: 1 };

const PANEL_VISUAL: ElementVisualDefinition = {
  textLike: false,
  cardCollection: false,
  autoTextScale: "none",
  hoverTarget: "surface",
  outlineTarget: "surface",
  glowTarget: "surface",
  shadowTarget: "surface",
  disableAutoHoverWhenUnconfigured: true,
  overflowVisibleInGrid: false,
};

/** Блоки «Стандарта», которые раньше жили в файлах ядра рядом с формой входа и оплатой. */
export const DEFAULT_EXTRA_BLOCKS: ElementDefinition[] = [
  {
    type: "defaultLoginForm",
    roles: ["selfScrolling"],
    label: "Форма входа (дефолт)",
    pack: "default",
    defaultData: {
      ...BASE_GRID,
      colSpan: GRID_COLUMNS,
      rowSpan: 12,
      headTag: "SN · /AUTH",
      title: "Вход",
      subtitle: "▸ Подключение к личному кабинету",
      tabPasswordLabel: "Пароль",
      tabCodeLabel: "Код на e-mail",
      emailLabel: "E-mail",
      emailPlaceholder: "you@solonet.io",
      passwordLabel: "Пароль",
      passwordPlaceholder: "••••••••••••",
      codeLabel: "Код из письма",
      codePlaceholder: "123456",
      showPwLabel: "показать",
      hidePwLabel: "скрыть",
      rememberLabel: "Запомнить",
      forgotLabel: "Забыли пароль?",
      forgotHref: "/reset-password",
      submitLabel: "Войти",
      sendCodeLabel: "Получить код",
      requestNewCodeLabel: "Запросить новый код",
      successLabel: "OK · туннель открыт",
      orLabel: "или",
      telegramLabel: "Telegram",
      googleLabel: "Google",
      yandexLabel: "Yandex",
      showPasswordLogin: true,
      showCodeLogin: true,
      showTelegramLogin: true,
      showGoogleLogin: true,
      showYandexLogin: true,
      legalText: "",
      successRedirect: "/dashboard",
      monoFontFamily: "JetBrains Mono, ui-monospace, monospace",
    },
    insert: [{ key: "defaultLoginForm", label: "Форма входа (дефолт)", description: "Вход по паролю, коду на почту, Telegram, Google и Яндекс.", category: "login" }],
    view: DefaultLoginFormBlockView,
    presentationCapability: FORM_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: {
      ...PANEL_VISUAL,
      overflowVisibleInGrid: true,
    },
  },
  {
    type: "defaultCheckout",
    label: "Оплата (дефолт)",
    pack: "default",
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 14,
      headerLabel: "К оплате",
      orderId: "",
      couponPlaceholder: "Промокод",
      couponApplyLabel: "Применить",
      couponOkPrefix: "✓",
      couponOkSuffix: "применён",
      couponErrorText: "Код неверен",
      couponLineLabel: "Промокод",
      totalLabel: "Итого",
      totalMeta: "оплата единоразовая",
      currency: "₽",
      baseAmount: 2988,
      payLabel: "Оплатить",
      termsText: "Нажимая «Оплатить», вы принимаете условия покупки и политику.",
      secureLeft: "Защищённый платёж",
      secureRight: "Visa · MC · МИР · USDT",
      successRedirect: "/dashboard",
      monoFontFamily: "",
      priceRows: [
        { label: "Цена за месяц", value: "399 ₽", variant: "strike" },
        { label: "Цена · 12 мес", value: "2 988 ₽", variant: "base" },
      ],
      coupons: [
        { code: "SOLO20", discountPercent: 20 },
        { code: "FRIEND15", discountPercent: 15 },
        { code: "WELCOME", discountPercent: 10 },
      ],
    },
    insert: [{ key: "defaultCheckout", label: "Оплата (дефолт)", description: "Карточка оплаты: промокод, итог и кнопка.", category: "checkout" }],
    view: DefaultCheckoutBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: {
      ...PANEL_VISUAL,
      overflowVisibleInGrid: true,
    },
  },
  {
    type: "defaultCheckoutBanner",
    roles: ["selfScrolling"],
    label: "Оплата: баннер (дефолт)",
    pack: "default",
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 12,
      useFlowData: true,
      breadcrumb: ["Кабинет", "Подписки", "Оплата"],
      headlineText: "Оплата",
      showDot: false,
      subtitle: "Доступ откроется в течение минуты после подтверждения платежа.",
      planCells: [
        { label: "Тариф", value: "PRO" },
        { label: "Период", value: "12 мес" },
        { label: "Устройств", value: "5" },
        { label: "Трафик", value: "Безлимит", accent: true },
      ],
      monoFontFamily: "",
    },
    insert: [{ key: "defaultCheckoutBanner", label: "Оплата: баннер (дефолт)", description: "Шапка страницы оплаты с предметом платежа.", category: "checkout" }],
    view: DefaultCheckoutBannerBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: {
      ...PANEL_VISUAL,
      overflowVisibleInGrid: true,
    },
  },
];
