import type { ElementDefinition, ElementVisualDefinition } from "@/components/constructor/elementDefinitions";
import { PANEL_PRESENTATION_CAPABILITY } from "@/components/constructor/presentation/elementCapabilityCatalog";
import { createLazyView } from "@/components/constructor/blockContent/lazyViews";

const DefaultReferralCardBlockView = createLazyView(() => import("../blockContent/DefaultReferralCardBlockView").then(m => ({ default: m.DefaultReferralCardBlockView })));
const DefaultReferralTierBlockView = createLazyView(() => import("../blockContent/DefaultReferralTierBlockView").then(m => ({ default: m.DefaultReferralTierBlockView })));
const DefaultFriendsListBlockView = createLazyView(() => import("../blockContent/DefaultFriendsListBlockView").then(m => ({ default: m.DefaultFriendsListBlockView })));
const DefaultPartnerPayoutsBlockView = createLazyView(() => import("../blockContent/DefaultPartnerPayoutsBlockView").then(m => ({ default: m.DefaultPartnerPayoutsBlockView })));
const DefaultPayoutRequestBlockView = createLazyView(() => import("../blockContent/payouts/DefaultPayoutRequestBlockView").then(m => ({ default: m.DefaultPayoutRequestBlockView })));
const DefaultPayoutHistoryBlockView = createLazyView(() => import("../blockContent/payouts/DefaultPayoutHistoryBlockView").then(m => ({ default: m.DefaultPayoutHistoryBlockView })));

const BASE_GRID = { col: 0, row: 0, zIndex: 0, fontScale: 1 };
const PACK = "default";
const MONO_FONT = "";

const PANEL_VISUAL: ElementVisualDefinition = {
  textLike: false,
  cardCollection: false,
  autoTextScale: "none",
  hoverTarget: "control",
  outlineTarget: "surface",
  glowTarget: "surface",
  shadowTarget: "surface",
  disableAutoHoverWhenUnconfigured: true,
  overflowVisibleInGrid: true,
};

/** Рефералы и партнёрская программа. */
export const DEFAULT_PARTNER_BLOCKS: ElementDefinition[] = [
  {
    type: "defaultReferralCard",
    label: "Стандарт: реф-карточка",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 7,
      monoFontFamily: MONO_FONT,
      panelHint: "Ваша реферальная ссылка",
      linkPrefix: "solonet.io/r/",
      copyLabel: "Копировать",
      copiedLabel: "Скопировано",
      shareLabel: "Поделиться",
      qrLabel: "QR-код",
      showShare: true,
      showQr: true,
    },
    view: DefaultReferralCardBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 7, data: {} },
    insert: [
      {
        key: "defaultReferralCard",
        category: "cabinet",
        label: "Рефералка: карточка ссылки",
        description: "Большой блок с реферальным кодом и ссылкой. Код тянется из /api/auth/summary.",
      },
      {
        key: "defaultReferralCardPartner",
        category: "cabinet",
        label: "Партнёрка: карточка ссылки",
        description: "Большой блок с партнёрским кодом и ссылкой. Тянется из /api/partners/qr.",
        data: { mode: "partner", panelHint: "Ваша партнёрская ссылка" },
      },
    ],
  },
  {
    type: "defaultReferralTier",
    label: "Стандарт: статистика реф-программы",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 10,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "Условия программы",
      panelHeaderHint: "",
      conditionsLabel: "Условия",
      showConditions: true,
      rows: [
        { label: "Приглашено", value: "0" },
        { label: "Активных", value: "0" },
        { label: "Заработано", value: "0 ₽" },
      ],
    },
    view: DefaultReferralTierBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 10, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultReferralTier",
        category: "cabinet",
        label: "Рефералка: статистика",
        description: "Панель статистики реферальной программы: приглашено / активных / заработано + условия из API.",
      },
      {
        key: "defaultReferralTierPartner",
        category: "cabinet",
        label: "Партнёрка: статистика",
        description: "Панель статистики партнёрской программы: приглашено / оплатили / баланс + условия из API.",
        data: { mode: "partner", panelHeader: "Условия партнёрки" },
      },
    ],
  },
  {
    type: "defaultFriendsList",
    label: "Стандарт: приведённые друзья",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "Приведённые друзья",
      panelHeaderHintFormat: "{count} человек",
      emptyText: "Пока нет рефералов",
      items: [
        { name: "solo_anya", plan: "PRIME · 12 мес", bonus: "+30 дн", ts: "2 дня назад" },
        { name: "mr_quiet", plan: "CORE · 6 мес", bonus: "+30 дн", ts: "1 нед назад" },
        { name: "ave", plan: "PROBE", bonus: "—", ts: "1 мес назад" },
      ],
    },
    view: DefaultFriendsListBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultFriendsList",
        category: "cabinet",
        label: "Рефералка: приведённые друзья",
        description: "Список приглашённых через реферальную программу. /api/referrals/list.",
      },
      {
        key: "defaultFriendsListPartner",
        category: "cabinet",
        label: "Партнёрка: приведённые партнёром",
        description: "Список приглашённых через партнёрскую программу. /api/partners/invited/me.",
        data: { mode: "partner", panelHeader: "Приведённые партнёром" },
      },
    ],
  },
  {
    type: "defaultPartnerPayouts",
    label: "Стандарт: партнёрка — заявки на вывод",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 18,
      rowSpan: 7,
      monoFontFamily: MONO_FONT,
      panelHeader: "Заявки на вывод",
      panelHeaderHintFmt: "баланс {balance} ₽",
      amountLabel: "Сумма к выводу",
      amountPlaceholder: "0",
      submitLabel: "Запросить",
      submittingLabel: "Отправляем...",
      successText: "✓ Заявка создана",
      errorText: "✕ Не удалось создать заявку",
      emptyText: "Заявок пока нет",
      loadingText: "Загрузка...",
      historyHeader: "История",
      statusPendingLabel: "В обработке",
      statusApprovedLabel: "Одобрено",
      statusRejectedLabel: "Отклонено",
      statusPaidLabel: "Выплачено",
      maxItems: 20,
      minAmount: 100,
      notEnoughBalanceText: "На балансе недостаточно средств",
      belowMinText: "Минимальная сумма {min} ₽",
    },
    view: DefaultPartnerPayoutsBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 7, data: {} },
    hiddenFromInsertMenu: true,
  },
  {
    type: "defaultPayoutRequest",
    label: "Стандарт: партнёрка — запрос на вывод",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 9,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "Запрос на вывод",
      panelHeaderHintFmt: "баланс {balance} ₽",
      amountLabel: "Сумма к выводу",
      amountPlaceholder: "0",
      submitLabel: "Запросить",
      submittingLabel: "Отправляем...",
      successText: "✓ Заявка создана",
      errorText: "✕ Не удалось создать заявку",
      loadingText: "Загрузка...",
      minAmount: 100,
      notEnoughBalanceText: "На балансе недостаточно средств",
      belowMinText: "Минимальная сумма {min} ₽",
      setupHint: "Чтобы выводить средства, укажите способ вывода и реквизиты.",
      setupCtaLabel: "Установить способ вывода",
      noMethodsText: "Способы вывода не настроены администратором.",
      methodSelectLabel: "Способ вывода",
      requisitesLabel: "Реквизиты",
      saveMethodLabel: "Сохранить",
      savingMethodLabel: "Сохраняем...",
      cancelLabel: "Отмена",
      changeMethodLabel: "изменить",
      methodSavedFmt: "{method} · {masked}",
    },
    view: DefaultPayoutRequestBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 9, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultPayoutRequest",
        category: "cabinet",
        label: "Партнёрка: запрос на вывод",
        description: "Способ вывода, реквизиты и создание заявки. PUT /api/partners/payout-method/me, POST /api/partners/payouts/me.",
        cabinetTabHints: ["partners"],
        priority: 10,
      },
    ],
  },
  {
    type: "defaultPayoutHistory",
    label: "Стандарт: партнёрка — история выводов",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 9,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "История выводов",
      panelHeaderHintFmt: "всего {count}",
      emptyText: "Заявок пока нет",
      loadingText: "Загрузка...",
      statusPendingLabel: "В обработке",
      statusApprovedLabel: "Одобрено",
      statusRejectedLabel: "Отклонено",
      statusPaidLabel: "Выплачено",
      maxItems: 20,
      pageSize: 4,
      pagePrevLabel: "Назад",
      pageNextLabel: "Вперёд",
      pageLabelFormat: "{page} / {total}",
    },
    view: DefaultPayoutHistoryBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 9, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultPayoutHistory",
        category: "cabinet",
        label: "Партнёрка: история выводов",
        description: "Список заявок со статусами и страницами. GET /api/partners/payouts/me.",
        cabinetTabHints: ["partners"],
        priority: 11,
      },
    ],
  },
];
