import type { ElementDefinition, ElementVisualDefinition } from "@/components/constructor/elementDefinitions";
import { PANEL_PRESENTATION_CAPABILITY } from "@/components/constructor/presentation/elementCapabilityCatalog";
import { createLazyView } from "@/components/constructor/blockContent/lazyViews";
import { DEFAULT_CONNECT_STEPS, appCatalogSeed, appStepsSeed } from "@/components/constructor/blockContent/appCatalog";

const DefaultTariffPanelBlockView = createLazyView(() => import("../blockContent/tariffPanel").then(m => ({ default: m.DefaultTariffPanelBlockView })));
const DefaultTariffSwitcherBlockView = createLazyView(() => import("../blockContent/DefaultTariffSwitcherBlockView").then(m => ({ default: m.DefaultTariffSwitcherBlockView })));
const DefaultConnectCtaBlockView = createLazyView(() => import("../blockContent/DefaultConnectCtaBlockView").then(m => ({ default: m.DefaultConnectCtaBlockView })));
const DefaultTrialCardBlockView = createLazyView(() => import("../blockContent/DefaultTrialCardBlockView").then(m => ({ default: m.DefaultTrialCardBlockView })));
const DefaultPaymentMethodBlockView = createLazyView(() => import("../blockContent/DefaultPaymentMethodBlockView").then(m => ({ default: m.DefaultPaymentMethodBlockView })));
const DefaultInvoiceListBlockView = createLazyView(() => import("../blockContent/DefaultInvoiceListBlockView").then(m => ({ default: m.DefaultInvoiceListBlockView })));

const BASE_GRID = { col: 0, row: 0, zIndex: 0, fontScale: 1 };
const PACK = "default";
const MONO_FONT = "";

const PANEL_VISUAL: ElementVisualDefinition = {
  textLike: false,
  cardCollection: false,
  autoTextScale: "none",
  hoverTarget: "control",
  outlineTarget: "surface",
  glowTarget: "surface",
  shadowTarget: "surface",
  disableAutoHoverWhenUnconfigured: true,
  overflowVisibleInGrid: true,
};

/** Подписка, тарифы и оплата. */
export const DEFAULT_SUBSCRIPTION_BLOCKS: ElementDefinition[] = [
  {
    type: "defaultTariffPanel",
    roles: ["noStyleTab", "segmentedLegacy"],
    label: "Стандарт: текущий тариф",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 14,
      rowSpan: 8,
      monoFontFamily: MONO_FONT,
      panelHeader: "Текущий тариф",
      panelHeaderHint: "PRIME",
      pricePrimary: "399",
      pricePeriodLabel: "₽ / мес",
      renewalText: "Списание 4 788 ₽ — 12 АПР 2027",
      features: [
        { label: "Серверы", value: "412" },
        { label: "Устройств", value: "10" },
        { label: "Multi-hop", value: "2 узла" },
        { label: "Поддержка", value: "Live · 24/7" },
      ],
      primaryButtonLabel: "Продлить",
      primaryButtonHref: "",
      addonsButtonLabel: "Докупить",
      addonsButtonHref: "",
      switchTariffLabel: "Сменить тариф",
      switchTariffHref: "/tariffs",
      switchTariffMode: "inside",
      switchTariffGroupCode: "",
      switchTariffEmptyText: "Доступных тарифов нет",
      switchTariffCurrentBadge: "Текущий",
      switchTariffUpgradeLabel: "Перейти →",
      switchTariffSelectLabel: "Выбрать",
      switchTariffBackLabel: "← Назад",
      switchTariffPerDayLabel: "в день",
      switchTariffsPerPage: 5,
      switchTariffPrevLabel: "← Пред",
      switchTariffNextLabel: "След →",
      switchTariffPageFormat: "{page} / {total}",
      checkoutSlug: "checkout",
      noKeysText: "Нет активной подписки",
      buyTariffLabel: "Купить тариф",
      renewalPrefix: "Истекает",
      labelDevices: "Устройств",
      labelTraffic: "Трафик",
      labelExpiry: "До",
      labelAlias: "Имя",
      trafficUnlimitedText: "∞",
      addonsDialogTitle: "Докупить опции",
      addonsDialogHint: "Доп. устройства/трафик к текущему тарифу",
      addonsDevicesLabel: "Устройства",
      addonsTrafficLabel: "Трафик",
      addonsTotalLabel: "Итого к оплате",
      addonsSubmitLabel: "Оформить",
      addonsCancelLabel: "Отмена",
      addonsUnavailableText: "Для текущего тарифа нет доступных опций",
    },
    view: DefaultTariffPanelBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 8, data: {} },
    insert: [
      {
        key: "defaultTariffPanel",
        category: "cabinet",
        label: "Стандарт: текущий тариф",
        description: "Панель с большой ценой, фичами и кнопками апгрейда/отмены.",
      },
    ],
  },
  {
    type: "defaultTariffSwitcher",
    label: "Стандарт: выбор тарифа",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 7,
      monoFontFamily: MONO_FONT,
      panelHeader: "Сменить тариф",
      panelHeaderHint: "",
      emptyText: "Тарифы не найдены",
      loadingText: "Загрузка...",
      errorText: "Не удалось загрузить тарифы",
      currentBadge: "Текущий",
      upgradeLabel: "Перейти →",
      downgradeLabel: "Сменить",
      switchLabel: "Выбрать",
      selectLabel: "Купить",
      checkoutSlug: "checkout",
      groupCode: "",
      showGroupTabs: true,
      perDayLabel: "в день",
      devicesLabel: "устр.",
      trafficLabel: "ГБ",
      unlimitedText: "∞",
    },
    view: DefaultTariffSwitcherBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 7, data: {} },
    insert: [
      {
        key: "defaultTariffSwitcher",
        category: "cabinet",
        label: "Стандарт: выбор тарифа",
        description: "Сетка доступных тарифов из /api/tariffs/public с подсветкой текущего и кнопкой Перейти.",
        cabinetTabHints: ["keys"],
        priority: 6,
      },
    ],
  },
  {
    type: "defaultTrialCard",
    label: "Стандарт: пробный период",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 12,
      rowSpan: 5,
      panelHint: "Пробный доступ",
      titleText: "Пробный период",
      freeLabel: "Бесплатно",
      ctaLabel: "Попробовать",
      usedLabel: "Уже использован",
      noTrialText: "Нет пробного тарифа в группе trial",
      loadingText: "Загрузка...",
      devicesUnit: "устр.",
      trafficUnit: "ГБ",
      unlimitedText: "Безлимит",
      backendVisibilityKey: "trialEnabled",
      respectBackendVisibility: true,
    },
    view: DefaultTrialCardBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 12, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultTrialCard",
        category: "cabinet",
        label: "Стандарт: пробный период",
        description: "Карточка пробного тарифа (группа trial) с активацией. Берёт самый новый триал.",
        cabinetTabHints: ["keys"],
        priority: 5,
      },
    ],
  },
  {
    type: "defaultConnectCta",
    label: "Стандарт: подключить",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 7,
      monoFontFamily: MONO_FONT,
      panelHint: "Подключение к VPN",
      fallbackTitle: "VPN",
      noKeysText: "Нет активной подписки",
      loadingText: "Загрузка...",
      connectLabel: "Подключить",
      copyLabel: "Копировать",
      copiedLabel: "Скопировано",
      shareLabel: "Поделиться",
      shareTitle: "Подключение к VPN",
      qrLabel: "QR-код",
      qrCloseLabel: "Закрыть QR",
      qrErrorText: "Не удалось загрузить QR",
      showConnect: true,
      showCopy: true,
      showLink: true,
      showShare: true,
      showQr: true,
      viewMode: "all",
      showAppPicker: true,
      platformTitle: "Ваше устройство",
      clientTitle: "Приложение",
      connectTitle: "Подключение",
      stepsTitle: "Что делать",
      downloadLabel: "Скачать",
      backLabel: "Назад",
      counterFormat: "Шаг {n} из {total}",
      noClientsText: "Для этой платформы приложений пока нет",
      labelIos: "iPhone / iPad",
      labelAndroid: "Android",
      labelWindows: "Windows",
      labelMacos: "macOS",
      labelLinux: "Linux",
      apps: appCatalogSeed(),
      steps: appStepsSeed(DEFAULT_CONNECT_STEPS),
    },
    view: DefaultConnectCtaBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 7, data: {} },
    insert: [
      {
        key: "defaultConnectCta",
        category: "cabinet",
        label: "Стандарт: подключить (CTA)",
        description: "Подключение: карточка со ссылкой, QR и выбором приложения либо пошаговый мастер. Тянет активный ключ из /api/keys.",
        cabinetTabHints: ["keys"],
        priority: 5,
      },
    ],
  },
  {
    type: "defaultPaymentMethod",
    label: "Стандарт: метод оплаты",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 10,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "Способ оплаты",
      panelHeaderHint: "основной",
      cardMask: "•••• •••• •••• 4 829",
      cardMeta: "Visa · истекает 11/28",
      changeLabel: "Сменить",
      changeHref: "/dashboard/profile",
      altMethodsLabel: "Другие методы",
      altMethods: [
        { label: "SBP" },
        { label: "BTC" },
        { label: "USDT" },
        { label: "MONERO" },
      ],
    },
    view: DefaultPaymentMethodBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 10, rowSpan: 6, data: {} },
    insert: [
      {
        key: "defaultPaymentMethod",
        category: "cabinet",
        label: "Стандарт: метод оплаты",
        description: "Панель с привязанной картой и альтернативными методами.",
      },
    ],
  },
  {
    type: "defaultInvoiceList",
    label: "Стандарт: история платежей",
    pack: PACK,
    defaultData: {
      ...BASE_GRID,
      colSpan: 24,
      rowSpan: 6,
      monoFontFamily: MONO_FONT,
      panelHeader: "Транзакции",
      panelHeaderHintFormat: "{count} записей",
      emptyText: "Платежей пока нет",
      loadingText: "Загрузка...",
      unauthenticatedText: "Войдите, чтобы увидеть историю",
      paidLabel: "Оплачен",
      pendingLabel: "PENDING",
      failedLabel: "FAIL",
      cancelledLabel: "CANCEL",
      pdfLabel: "PDF",
      maxItems: 20,
      showAdjustments: false,
    },
    view: DefaultInvoiceListBlockView,
    presentationCapability: PANEL_PRESENTATION_CAPABILITY,
    allowInModal: false,
    inspector: { showGenericHoverControls: false },
    visual: PANEL_VISUAL,
    preview: { colSpan: 18, rowSpan: 5, data: {} },
    insert: [
      {
        key: "defaultInvoiceList",
        category: "cabinet",
        label: "Стандарт: история платежей",
        description: "Список оплат из /api/payments в моно-стиле.",
      },
    ],
  },
];
